### ISSUE TITLE
Example code to list all pages?

### ISSUE THREAD

**Issue by dheera** [makenotion/notion-sdk-js#100]
How do I list all pages and get the hierarchy? Is there an example to do this?

**Comment by ckim328** [comment]
I believe you are looking for this https://developers.notion.com/reference/post-search
To list all the pages within the integration (and their respective sub pages), don't query anything!

**Comment by dastasoft** [comment]
I achieve that doing:

```js
const response = await notion.databases.query({
    database_id: process.env.NOTION_DATABASE_ID!,
  })
```

Is there any problem using the query?

**Comment by dheera** [comment]
@dastasoft How do I know what the NOTION_DATABASE_ID is?
I tried using `notion.databases.list()` and it just returns an empty list, not even a single database.

**Comment by dheera** [comment]
@ckim328 I tried that, it returned nothing:
```
(async () => {
  const response = await notion.search();
  console.log("search", response);
})();
```

Output:
```
search { object: 'list', results: [], next_cursor: null, has_more: false }
```

**Comment by dastasoft** [comment]
> @dastasoft How do I know what the NOTION_DATABASE_ID is?
> I tried using `notion.databases.list()` and it just returns an empty list, not even a single database.

I use that same function, the other option is using notion.search because list is being deprecated. If you don't see any database maybe you're not sharing your Notion with an integration, check the initial steps and try with postman the different endpoints before diving into the JS.

**Comment by dheera** [comment]
@dastasoft `search()` also returns nothing for me. How does one share with an integration? I never saw that step, and can't seem to find the answer anywhere in the docs.

**Comment by dheera** [comment]
Never mind, I found it, apparently you have to "invite" the integration after "adding" the integration, and have to do this for every page I suppose. It's super non-intuitive but it worked. I was hoping for just superuser access to the entire account. Thanks!

**Comment by adelin-b** [comment]
> Never mind, I found it, apparently you have to "invite" the integration after "adding" the integration, and have to do this for every page I suppose. It's super non-intuitive but it worked. I was hoping for just superuser access to the entire account. Thanks!

Maybe the error message could display this `You need to share the page to the integration`
