### ISSUE TITLE
Unable to make a create page request  - 'Object.fromEntries is not a function'

### ISSUE THREAD

**Issue by Nlorio** [makenotion/notion-sdk-js#106]
**Describe the bug**
I receive the following error when trying to make a create page requests using the NodeJS library. I am making the request inside of my NodeJS app. I am positive that the database is linked as I am able to add entries to the database if I use cURL or if I write the http request manually using axios. 

See below for the request which is resulting in the error.
```
const notion = new Client({                       
  auth: process.env.NOTION_TOKEN,
  logLevel: LogLevel.DEBUG,  
})
```

```
router.post('/api/post/addentry',` (req, res) => {
let data = {
    parent: {
      database_id: process.env.DB_ID,
    },
    properties: {
      Name: {
        type: 'title',
        title: [
          {
            text: {
              content: name,
            },
          },
        ],
      },
      Date: {
        date: {
          start: date,
        },
      },
      Completed: {
        select: { name: completed },
      },
    },
  };

  (async () => {
    try {
      console.log(data);
      const response = await  notion.pages.create(data);
      console.log(response);
      res.send('Entry Added');
    } catch (error) {
      if (error.code === APIErrorCode.ObjectNotFound) {
        //
        // For example: handle by asking the user to select a different database
        //
        res.send('Object not found');
      } else {
        // Other error handling code
        console.error(error)
        res.send('Error');
      }
    }
  })();
})
```

_TypeError: Object.fromEntries is not a function_

**Terminal Error Output**
![bug](https://user-images.githubusercontent.com/15060677/119604550-1df7d700-bda4-11eb-83cd-d0e111f078bb.png)

I have followed the documentation here for format: 
- https://developers.notion.com/reference/post-page
- https://developers.notion.com/docs/working-with-databases

**To Reproduce**
Node version: 10.19.0
Express version: ~4.16.1
axios version: ^0.21.1
Notion JS library version: ^0.1.8

**Expected behavior**
Expect new page to be created and added to the linked database.
![database](https://user-images.githubusercontent.com/15060677/119605641-fb66bd80-bda5-11eb-858c-16c913f03017.png)

**Comment by kyleCodein** [comment]
> **Describe the bug**
> I receive the following error when trying to make a create page requests using the NodeJS library. I am making the request inside of my NodeJS app. I am positive that the database is linked as I am able to add entries to the database if I use cURL or if I write the http request manually using axios.
> 
> See below for the request which is resulting in the error.
> 
> ```
> const notion = new Client({                       
>   auth: process.env.NOTION_TOKEN,
>   logLevel: LogLevel.DEBUG,  
> })
> ```
> 
> ```
> router.post('/api/post/addentry',` (req, res) => {
> let data = {
>     parent: {
>       database_id: process.env.DB_ID,
>     },
>     properties: {
>       Name: {
>         type: 'title',
>         title: [
>           {
>             text: {
>               content: name,
>             },
>           },
>         ],
>       },
>       Date: {
>         date: {
>           start: date,
>         },
>       },
>       Completed: {
>         select: { name: completed },
>       },
>     },
>   };
> 
>   (async () => {
>     try {
>       console.log(data);
>       const response = await  notion.pages.create(data);
>       console.log(response);
>       res.send('Entry Added');
>     } catch (error) {
>       if (error.code === APIErrorCode.ObjectNotFound) {
>         //
>         // For example: handle by asking the user to select a different database
>         //
>         res.send('Object not found');
>       } else {
>         // Other error handling code
>         console.error(error)
>         res.send('Error');
>       }
>     }
>   })();
> })
> ```
> 
> _TypeError: Object.fromEntries is not a function_
> 
> **Terminal Error Output**
> ![bug](https://user-images.githubusercontent.com/15060677/119604550-1df7d700-bda4-11eb-83cd-d0e111f078bb.png)
> 
> I have followed the documentation here for format:
> 
> * https://developers.notion.com/reference/post-page
> * https://developers.notion.com/docs/working-with-databases
> 
> **To Reproduce**
> Node version: 10.19.0
> Express version: ~4.16.1
> axios version: ^0.21.1
> Notion JS library version: ^0.1.8
> 
> **Expected behavior**
> Expect new page to be created and added to the linked database.
> ![database](https://user-images.githubusercontent.com/15060677/119605641-fb66bd80-bda5-11eb-858c-16c913f03017.png)

change node version to 12.0.0 or above

**Comment by Nlorio** [comment]
Thanks! You are correct, I updated my node version and everything works as expected.
