### ISSUE TITLE
Date mention Typescript bug

### ISSUE THREAD

**Issue by terrygonguet** [makenotion/notion-sdk-js#109]
The `DateMention` interface says its `date` property is a `DatePropertyValue` but the API just returns an object with `start` and `end` properties.

```typescript
interface DateMention {
    type: "date";
    date: DatePropertyValue;
}

interface DatePropertyValue extends PropertyValueBase {
    type: "date";
    date: {
        start: string;
        end?: string;
    };
}
```

But the returned mention object looks like:

```javascript
{ type: 'date', date: { start: '2021-05-29', end: null } }
```

The other Mention types just have the data in the typed key.

**Comment by rhart92** [comment]
Now that the types are auto-generated this should be resolved 🙏
