### ISSUE TITLE
Incorrect types when using formula

### ISSUE THREAD

**Issue by sharpn** [makenotion/notion-sdk-js#113]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API, please reach out to support by going to [developers.notion.com](https://developers.notion.com), scroll to the bottom and click on `Help`.

**Describe the bug**
When using the formula filter there is 1 level too much nesting in the type

**To Reproduce**
Node version: 14
Notion JS library version: 0.1.8

attempt to search a function column in a database.

following the types it wants you to write

```
formula: {
  number: {
    number: {
       equals: 1,
   }
  },
},
```

this looks as tho it is because the formula object uses the filters e.g. `NumberFilter` which also have a property e.g. `number?` also defined in them

**Expected behavior**
should accept the following 
```
formula: {
   number: {
      equals: 1,
   },
}
```

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by reflash** [comment]
I've noticed that when trying to filter by formula value

The following is accepted by typescript, but fails on request
```typescript
{ property: 'Completed', formula: { checkbox: { checkbox: { equals: true } } } },
```

```
@notionhq/client warn: request fail {
[2021-09-24T11:19:21.261Z]   code: 'validation_error',
[2021-09-24T11:19:21.263Z]   message: 'body failed validation. Fix one: body.filter.and[0].formula.checkbox.equals should be defined, instead was `undefined`. body.filter.and[0].formula.checkbox.does_not_equal should be defined, instead was `undefined`.'
[2021-09-24T11:19:21.265Z] }
```

This works, but I had to use any
```
{ property: 'Completed', formula: { checkbox: { equals: true } as any} },
```

**Comment by rhart92** [comment]
All of the types are now generated directly from the source code after v0.4.0 of the API which should solve this typing issue.
