### ISSUE TITLE
Notion search API not getting pages form database. Only when I updated them (maybe an import issue from external sources?)

### ISSUE THREAD

**Issue by mvaneijgen** [makenotion/notion-sdk-js#114]
I have a search script that queries one specific database with pages, that should filter all pages that match the search query, but it doesn't seem to work as expected. I've done a few queries now, but have found one that should give results and it doesn't. Only when I manually update a note it will be in the results. To better illustrate my issue I've made a screencast. (see below)

**To Reproduce**
Node version: v14.15.1
Notion JS library version: 0.1.8

```
import { Client } from "@notionhq/client"
import { config } from "dotenv"
// const { Client } = require('d@notionhq/client');
config()
const notion = new Client({ auth: process.env.NOTION_API_KEY });

(async () => {
  const response = await notion.search({
    query: 'untitled',
    page_size: 100
  });
  console.warn(response);
})();
```

**Expected behavior**
List of all my pages with '...untitled...' in the name

**Screencast**
[![66Hst-mSdsQ](https://img.youtube.com/vi/66Hst-mSdsQ/0.jpg)](https://www.youtube.com/watch?v=66Hst-mSdsQ)

**Additional context**
My thought is that most of these pages (maybe all) are imported from Dropbox paper and/or Evernote and maybe there in lies the issue?

**Comment by rhart92** [comment]
Hi @mvaneijgen, we have been working to improve our search API over the last couple of months so hopefully this issue has been resolved.
