### ISSUE TITLE
Fetch page as Markdown

### ISSUE THREAD

**Issue by dyegoaurelio** [makenotion/notion-sdk-js#116]
It would be really useful if there was a method to fetch a whole page as Markdown
Since there's already a way to do it on the website, I don't think it would be too much trouble adding it to the public api
Are there any plans to implement this officially?

**Comment by alicial** [comment]
We have this feature on our roadmap, but don't yet have a timeline for adding it. Thank you for the feedback!

**Comment by sorrentix** [comment]
Hey @alicial any update on when this feature will be available?
Thanks!

**Comment by theolivenbaum** [comment]
Also interested - we would like to integrate notion in our app and having the html or markdown export would make things a lot easier!

**Comment by Kessir** [comment]
Also interested!

**Comment by cameronldroberts** [comment]
@alicial Hey :) +1 to this feature request. It would be really useful!

**Comment by theolivenbaum** [comment]
Also interested, having to read each page block by block is incredibly slow due to the low API rate limits

**Comment by metaskills** [comment]
> We have this feature on our roadmap, but don't yet have a timeline for adding it. Thank you for the feedback!

Where is the roadmap?

**Comment by yukukotani** [comment]
This might help you guys

https://github.com/yukukotani/fetch-notion-page
