### ISSUE TITLE
"Formula" property type detects all the "Rollup" dates format as String.

### ISSUE THREAD

**Issue by GuerreroC** [makenotion/notion-sdk-js#117]
Hi all,

**Describe the bug**
I created a "Relation" property type in a table to see the date from another table, so I set a column with the "Rollup" prop type of a Date type "Tentative" like this:

<img width="458" alt="Screen Shot 2021-06-08 at 0 47 51" src="https://user-images.githubusercontent.com/41349323/121130730-6c6d9280-c7f4-11eb-8481-bf30a4527b23.png">

Then, in the column "Delayed?" I selected the "Formula" type to compare the date and when I tried to set the formula, all properties are as String, so "Started" and "Tentative" are String type instead of Date type format.

<img width="498" alt="Screen Shot 2021-06-08 at 1 01 53" src="https://user-images.githubusercontent.com/41349323/121131674-bf941500-c7f5-11eb-8e73-37a76ebde5ec.png">

**Additional context**
So, If I try using these properties in a Date Formula it shows like this:

<img width="420" alt="Screen Shot 2021-06-08 at 1 11 17" src="https://user-images.githubusercontent.com/41349323/121132211-785a5400-c7f6-11eb-8665-71e40610e48b.png">

**Comment by justjake** [comment]
Hey, this seems to be a feature request about the Notion product, not the NodeJS client library. Please send feedback through the `? > Chat with us` inside Notion or by emailing team@makenotion.com.

You can find more help with the product here: https://www.notion.so/notion/Help-Support-e040febf70a94950b8620e6f00005004

**Comment by htobon** [comment]
I think one trick is to transform the date into a timestamp and then transform it back to date.
Something like:
`fromtimestamp(timestamp(prop("xxxxx"))`

That would return a date type which can be used to make date calculations.

**Comment by hojungan** [comment]
> I think one trick is to transform the date into a timestamp and then transform it back to date. Something like: `fromtimestamp(timestamp(prop("xxxxx"))`
> 
> That would return a date type which can be used to make date calculations.
