### ISSUE TITLE
How I can insert a link in a Notion table?

### ISSUE THREAD

**Issue by wahibAbdouWbs** [makenotion/notion-sdk-js#119]
I tried to insert a text and a link into a Notion table it did work with the text but it didn't with the website link?
this is my express POST route any help?
![Screen Shot 2021-06-08 at 17 12 49](https://user-images.githubusercontent.com/80881400/121220778-d762ac00-c87c-11eb-801f-49a41d10a06f.png)
Notion Table:
![Screen Shot 2021-06-08 at 17 14 19](https://user-images.githubusercontent.com/80881400/121220953-00833c80-c87d-11eb-8441-8586658070d0.png)

**Comment by yassinebridi** [comment]
URLs can be inserted without content, and without brackets, so just like this:
```js
  Website: { url: req.body.website },
```

**Comment by wahibAbdouWbs** [comment]
Unfortunately didn't work I have no idea why but I will just insert it all as text type. Thanks 🙏

**Comment by huuphongnguyen** [comment]
@wahibAbdouWbs Did you got any example code write to Notion Database using Next.js or React? Thank you so much.

**Comment by wahibAbdouWbs** [comment]
> @wahibAbdouWbs Did you got any example code write to Notion Database using Next.js or React? Thank you so much.

I did develop a separated API backend from my front-end I'm not sure if it is possible to do that directly using notion-sdk-js.

**Comment by yassinebridi** [comment]
This is straight from my personal website:
I'm using the Fetch API directly since this library is not playing nice with Next.js
`/api/create-contact`:
```ts
import { createPage, databasesId } from '@lib';
import { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const { Name, Email, Company, Content, Deadline, Brief } = req.body;
  const newContact = await createPage({
    parent: { database_id: databasesId.sections.contact },
    properties: {
      Name: {
        title: [
          {
            text: {
              content: Name,
            },
          },
        ],
      },
      Email: {
        rich_text: [
          {
            text: {
              content: Email,
            },
          },
        ],
      },
      Company: {
        rich_text: [
          {
            text: {
              content: Company,
            },
          },
        ],
      },
      Content: {
        rich_text: [
          {
            text: {
              content: Content,
            },
          },
        ],
      },
      Deadline: {
        select: {
          name: Deadline,
        },
      },
      Brief: { url: Brief },
    },
  });

  return res.status(200).json({
    ok: true,
    data: newContact,
  });
}
```
And the `createPage` is defined like this:
```
const notionBaseApi = 'https://api.notion.com/v1';

const fetchConfig: RequestInit = {
  headers: {
    Authorization: `Bearer ${process.env.NOTION_TOKEN}`,
    'Notion-Version': '2021-05-13',
  },
};

export const createPage = async (
  args: WithAuth<PagesCreateParameters>
): Promise<PagesCreateParameters> => {
  const res = await fetch(`${notionBaseApi}/pages`, {
    ...fetchConfig,
    headers: {
      ...fetchConfig.headers,
      'Content-Type': 'application/json',
    },
    method: 'post',
    body: JSON.stringify(args),
  });
  const data = await res.json();
  return data;
};
```
