### ISSUE TITLE
How to create views for linked databases using the API?

### ISSUE THREAD

**Issue by nanbhas** [makenotion/notion-sdk-js#121]
I have a bunch of databases with similar properties. I have a page which contains the linked databases. How can I programmatically set the views (e.g. board view with sort and filter, etc) using the API?

**Comment by alicial** [comment]
We don't support database views currently in the API. This is on our roadmap, but we don't have a timeline for adding this feature yet. Thanks for the feedback!

**Comment by divramod** [comment]
hey @alicial. is there any update on that. It would be a really really useful feature for me ;-)

**Comment by uiii** [comment]
What about today? I am looking for this too.

**Comment by dev-traveler** [comment]
Add me to the waitlist for this feature

**Comment by williamrcesar** [comment]
I’m also very interested in this enhancement. My main use case is duplicating existing pages. I need to clone a page (including its blocks and structure) so I can use it as a template. Currently this isn’t possible via the API, which prevents me from automating the workflow.
