### ISSUE TITLE
Unable to submit page property with relation properties

### ISSUE THREAD

**Issue by gulfaraz** [makenotion/notion-sdk-js#124]
**Describe the bug**
Unable to cast a relation property to [`InputPropertyValue`](https://github.com/makenotion/notion-sdk-js/blob/4871fc7c3f33370792b9917feee68e2f1f50a9c4/src/api-types.ts#L574)
[`InputPropertyValue`](https://github.com/makenotion/notion-sdk-js/blob/4871fc7c3f33370792b9917feee68e2f1f50a9c4/src/api-types.ts#L574) is required for [`InputPropertyValueMap`](https://github.com/makenotion/notion-sdk-js/blob/4871fc7c3f33370792b9917feee68e2f1f50a9c4/src/api-endpoints.ts#L168)
[`InputPropertyValueMap`](https://github.com/makenotion/notion-sdk-js/blob/4871fc7c3f33370792b9917feee68e2f1f50a9c4/src/api-endpoints.ts#L168) is required for [`notion.pages.create properties`](https://github.com/makenotion/notion-sdk-js/blob/main/src/api-endpoints.ts#L172)
Thus, I'm unable to submit a page create request with a relation property.

**To Reproduce**
Node version: v14.16.0
Notion JS library version: v0.1.9

Steps to reproduce the behaviour:
1. Create a relation property object as described in [this SO answer](https://stackoverflow.com/a/67915840/1753041).
```
{
    relation: [
        {
            id: 'dc50a136-75e5-4241-81a8-d8d815ad4673',
        },
    ],
} as InputPropertyValue
```
2. Call [pages.create](https://github.com/makenotion/notion-sdk-js/blob/f6f5a0cae2abb31f8a44a700cdc008b07cc5a29d/src/Client.ts#L248) with the above relation property as a value.
3. a) See typescript error either in step 1
```
Conversion of type '{ relation: { id: string | undefined; }[]; }' to type 'InputPropertyValue' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
Type '{ relation: { id: string | undefined; }[]; }' is not comparable to type 'Omit<LastEditedByPropertyValue, "id"> & { id?: string | undefined; }'.
Type '{ relation: { id: string | undefined; }[]; }' is missing the following properties from type 'Omit<LastEditedByPropertyValue, "id">': type, last_edited_byts(2352)
```
3. b) If you choose to not define types then you get this error instead on [pages.create](https://github.com/makenotion/notion-sdk-js/blob/f6f5a0cae2abb31f8a44a700cdc008b07cc5a29d/src/Client.ts#L248)
```
  Property 'Race' is incompatible with index signature.
    Type '{ relation: { id: string | undefined; }[]; }' is not assignable to type 'InputPropertyValue'.
      Type '{ relation: { id: string | undefined; }[]; }' is not assignable to type 'Omit<LastEditedByPropertyValue, "id"> & { id?: string | undefined; }'.
        Type '{ relation: { id: string | undefined; }[]; }' is missing the following properties from type 'Omit<LastEditedByPropertyValue, "id">': type, last_edited_by
```

**Expected behaviour**
I should be able to submit a [pages.create](https://github.com/makenotion/notion-sdk-js/blob/f6f5a0cae2abb31f8a44a700cdc008b07cc5a29d/src/Client.ts#L248) request with a valid relation property.

**Additional context**
My workaround is to add a relation type to `api-types.d.ts`,
```
export interface RelationInputPropertyValue extends PropertyValueBase {
    type: "relation";
    relation: RelationInputProperty[];
}
export interface RelationInputProperty {
    id: string;
}
```
[See usage here.](https://github.com/gulfaraz/npc-generator/blob/feat.race_relation/main.ts#L163-L169)

**Comment by Morgan-Swanson** [comment]
This is really annoying and relation is poorly documented. Any way to create a relation based on database id and page title?

**Comment by rhart92** [comment]
Hi @gulfaraz, thank you for patience with this issue. We now generate our API types directly from our source code which should resolve this issue.
