### ISSUE TITLE
Unable to submit page with relation property

### ISSUE THREAD

**Issue by Morgan-Swanson** [makenotion/notion-sdk-js#126]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API, please reach out to support by going to [developers.notion.com](https://developers.notion.com), scroll to the bottom and click on `Help`.

**Describe the bug**
When using the SDK, I'm getting strange errors when trying to add a relation property.

**To Reproduce**
Node version: v14.17.1
Notion JS library version: 0.2.0

I'm using the create page endpoint.

When submitting a relation with the following format:
`relation: [
                        {
                            database_id: organization_database,
                            synched_property_name: event.Company
                        }
]`

I get the following response

`
  body: '{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one: body.properties.Organization.relation[0].text should be defined, instead was `undefined`. body.properties.Organization.relation[0].mention should be defined, instead was `undefined`. body.properties.Organization.relation[0].equation should be defined, instead was `undefined`. body.properties.Organization.relation[0].id should be defined, instead was `undefined`. body.properties.Organization.relation[0].name should be defined, instead was `undefined`."}'`

Am I missing something?  
**Expected behavior**
I expect to insert a new page with a relation to the database given with the name given. 

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by almawang** [comment]
relation properties should be the related page id, see the [documentation](https://developers.notion.com/reference/property-value-object#relation-property-values) for more information
