### ISSUE TITLE
Type of "checkbox" of CheckboxProperty should be boolean not Record<string, never>

### ISSUE THREAD

**Issue by houfu** [makenotion/notion-sdk-js#134]
**Describe the bug**
Type of Checkbox Propery is :
```
export interface CheckboxProperty extends PropertyBase {
  type: "checkbox"
  checkbox: Record<string, never>
}
```

Since the "checkbox" already returns a boolean, the type should be a boolean

**Comment by rhart92** [comment]
API Types are now auto-generated based on our source code so this issue should be resolved.
