### ISSUE TITLE
In-built retry mechanism in case of rate_limited error.

### ISSUE THREAD

**Issue by GorvGoyl** [makenotion/notion-sdk-js#137]
It'd be nice if this client could add the in-built mechanism of retry in case of any rate_limited errors like (i.e. >3req/sec). 
Since it's a common task whoever is consuming Notion API, I think it should be handled at client library level.
You could also add `exponential back off` strategy to reduce load on Notion servers. 

For reference, see Google node sdk: https://github.com/googleapis/nodejs-googleapis-common/pull/104

**Comment by alicial** [comment]
Thanks for the feedback, we will consider adding this in the future!
