### ISSUE TITLE
'Description is expected to be rich_text.' - using example code from documentation

### ISSUE THREAD

**Issue by thisisnotawill** [makenotion/notion-sdk-js#138]
**Describe the bug**
The example in the Notion API documentation to create a page with properties does not work for text properties. It looks like a rich text object needs to be provided in the request.

**To Reproduce**
Node version: 14.17.1
Notion JS library version: 

1. Create a db, add a text "Description" column
2. Copy the example code from documentation, remove all other properties such as "Price". 

**Expected behavior**
A new page should be created with a Description property of "A dark green leafy vegetable"

**Additional context**

The API response
```
Request returns Client warn: request fail {
code: 'validation_error',
message: 'Description is expected to be rich_text.'
}
```

The code that I am running. This is straight out of the documentation except I am isolating the "Description" text property.
```
import { Client } from "@notionhq/client";

const notion = new Client({ auth: process.env.NOTION_KEY });

const databaseId = process.env.NOTION_DATABASE_ID;

(async () => {
  const response = await notion.pages.create({
    parent: {
      database_id: databaseId,
    },
    properties: {
      Name: {
        title: [
          {
            text: {
              content: "Tuscan Kale",
            },
          },
        ],
      },
      Description: {
        text: [
          {
            text: {
              content: "A dark green leafy vegetable",
            },
          },
        ],
      },
    },
    children: [
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          text: [
            {
              type: "text",
              text: {
                content: "Lacinato kale",
              },
            },
          ],
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          text: [
            {
              type: "text",
              text: {
                content:
                  "Lacinato kale is a variety of kale with a long tradition in Italian cuisine, especially that of Tuscany. It is also known as Tuscan kale, Italian kale, dinosaur kale, kale, flat back kale, palm tree kale, or black Tuscan palm.",
                link: {
                  url: "https://en.wikipedia.org/wiki/Lacinato_kale",
                },
              },
            },
          ],
        },
      },
    ],
  });
  console.log(response);
})();
```

**Comment by maxmarkus** [comment]
Similar issue here, but didn't even find this documentation example from above. But the changelog shows how to set a text field (which apparently always is rich_text, even if you only want to store some plain_text). 
I have used the example from here: 
https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted#breaking-changes-in-version-2021-05-13
```
  const properties = {
    "Description": {
      "type": "rich_text",
      "rich_text": [
        {
          "type": "text",
          "text": { "content": "Hello World" }
        }
      ]
    }

   result = await this.notion.request({
        path: "pages",
        method: "POST",
        body: {
          parent: { database_id: this.databaseId },
          properties
        },
      })
 ```
 Which returns an error:
 > body failed validation. Fix one: body.properties.myfield.id should be defined, instead was `undefined`. body.properties.myfield.name should be defined, instead was `undefined`. body.properties.myfield.start should be defined, instead was `undefined`.

**Comment by 100kimch** [comment]
Example code on 'Pages > [POST] Create a Page > 200 Success - Create a Page' seems to be wrong due to [Breaking changes in version 2021-05-13](https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted#breaking-changes-in-version-2021-05-13)

Should the example be fixed. This confuses the API structure.

**Comment by almawang** [comment]
Thanks for the report! this has been fixed in the documentation

**Comment by kzkhykw** [comment]
@almawang 
> > body failed validation. Fix one: body.properties.myfield.id should be defined, instead was `undefined`. body.properties.myfield.name should be defined, instead was `undefined`. body.properties.myfield.start should be defined, instead was `undefined`.

I have a same issue here. How can I fix it?
