### ISSUE TITLE
title type when create page

### ISSUE THREAD

**Issue by jackluson** [makenotion/notion-sdk-js#141]
it fail when creating page, as follow:
![image](https://user-images.githubusercontent.com/36684351/124869293-91237880-dff3-11eb-828c-e61d6cb57ad4.png)

it success where create page. as follow:
![image](https://user-images.githubusercontent.com/36684351/124869498-e2cc0300-dff3-11eb-8b25-71d5a7b71264.png)

**Comment by rhart92** [comment]
The issue you are describing has been resolved in newer versions of the API.
