### ISSUE TITLE
Unable to add URL property value to a page in a database

### ISSUE THREAD

**Issue by peterMonteer** [makenotion/notion-sdk-js#151]
**Describe the bug**
I'm working with the notion-github-sync example. When I try to update or create a new page in a database with a URL property I receive the following error: 

`body: '{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one: body.properties.GitHub URL.id should be defined, instead was `undefined`. body.properties.GitHub URL.name should be defined, instead was `undefined`. body.properties.GitHub URL.start should be defined, instead was `undefined`."}' `

this is is the simple change I made, both for the patch and post method:

```
body: {
          properties: {
            State: { name: issues_details.state },
            "Issue Number": parseInt(issue_number),
            "GitHub URL": {
              url: "www",
            },
            Name: [{ text: { content: issues_details.title } }],
            Comments: parseInt(issues_details.comments),
          },
        },
```

If I try to manually add an id or some other parameter to "GitHub URL" the error changes to:

@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'Body Validation Failed. Fix the following:\n' +
    'Invalid property value for: "GitHub URL".'
}

I also played with the Postman collection, and the request to update a page only works if the only body param is the URL, if I try to update more parameters it doesnt work. This makes me think that the problem is with Notions API.

**To Reproduce**
Node version: v14.15.4
Notion JS library version: "^0.2.1"

Setup the notion-github-sync example, with a notion database with an additional column that holds a property of the type URL
Update the body properties of the notion request ( line 59 to 87 of the index.js) to send a URL property with the format:

body: {
          properties: {
            State: { name: issues_details.state },
            "Issue Number": parseInt(issue_number),
            "YOURCOLUMNURLNAME": {
              url: "RANDOMEXAMPLEURL",
            },
            Name: [{ text: { content: issues_details.title } }],
            Comments: parseInt(issues_details.comments),
          },
        },
```

**Expected behavior**
The creation and update of URL property fields should work.

**Comment by cwang314** [comment]
Hi @peterMonteer, thanks for the API bug report and apologies for the delayed response. _If I had to guess, you're actually calling the update database endpoint when you should be calling the create page endpoint._

That said, I'm closing this issue because this is an issue with the API whereas we want the issues in this github repo to be SDK-specific. However, you can submit bugs and feature requests for the API through Intercom by going to https://developers.notion.com/ and clicking "Help" in the footer.
