### ISSUE TITLE
Typescript error: properties.Date.date does not exist

### ISSUE THREAD

**Issue by ZeroPie** [makenotion/notion-sdk-js#154]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@notion.com.

**Describe the bug**
date should be set as optional on the type 
![Screenshot 2021-07-17 at 12 23 54](https://user-images.githubusercontent.com/8741666/126044971-f1b04501-628f-4e30-ad5c-4ab94f5ca03d.png)

**To Reproduce**
Node version: 14.15.1
Notion JS library version: "0.0.1"

![Screenshot 2021-07-17 at 12 23 54](https://user-images.githubusercontent.com/8741666/126044971-f1b04501-628f-4e30-ad5c-4ab94f5ca03d.png)

**Expected behavior**
date is declared as an optional type of Date

**Comment by zaerald** [comment]
hi @JorgeArreolaS, I'm fairly new to Typescript

I have here a sample structure for the `select` type that comes from `QueryDatabaseResponse`:
```
...
  Category: {
    id: '...',
    type: 'select',
    select: {
      id: '...',
      name: 'Test',
      color: 'blue'
    }
  }
...
```

When I use `if (type === 'select')` the type works fine:
```
  db.results
    .map(it => it.properties)
    .map(it => it.Category)
    .map(it => {if (it.type === 'select') return it.select})
```

**BUT** when I filter them with the type, it fails:
```
  db.results
...
    .filter(it => it.type === 'select')
    .map(it => it.select)
```

error:
```
Type error: Property 'select' does not exist on type '{ type: "title"; title: ({ type: "text"; text: { content: string; link: { url: string; } | null; }; annotations: { bold: boolean; italic: boolean; strikethrough: boolean; underline: boolean; code: boolean; color: "default" | ... 17 more ... | "red_background"; }; plain_text: string; href: string | null; } | { ...; }...'.
  Property 'select' does not exist on type '{ type: "title"; title: ({ type: "text"; text: { content: string; link: { url: string; } | null; }; annotations: { bold: boolean; italic: boolean; strikethrough: boolean; underline: boolean; code: boolean; color: "default" | ... 17 more ... | "red_background"; }; plain_text: string; href: string | null; } | { ...; }...'.

  82 |
  83 |     .filter(it => it.type === 'select')
> 84 |     .map(it => it.select)
     |                   ^
info  - Checking validity of types .%
```

**Comment by JorgeArreolaS** [comment]
Hi @zaerald, Im drinking coffee too.

A bit weird the typescript thing.
At first, a tip here
Instead of
```ts
    .map(it => {if (it.type === 'select') return it.select})
```
you can use an AND operator
```ts
    .map( it => it.type === 'select' && it.select )
```
In case the ` it.type === 'select'` is false, the map will return `false`, and `it.select` will not be executed, typescript will be happy.
Also you can set a default value with the OR operator at the end
```ts
    .map( it => condition && value || default )
```
The same with the [inline operator](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)
```ts
    .map( it => condition ? value : default )
```

---

with the `filter` think, I dont think typescript can automatically infer types when you filter an array

It is logic at runtime that after you filter the properies with an specific type, all the elements with have that type. So, is not as much recommended but you can use a typescript flag to let him know that you know there will be an error but its fine.

```
  db.results
    ...
    .filter(it => it.type === 'select')
    //@ts-expect-error
    .map(it => it.select)
```
More information at this [docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments)

**Comment by zaerald** [comment]
@JorgeArreolaS thanks for the tip 👌, and this now makes sense for the `filter` error that I encounter.

**Comment by Niceplace** [comment]
@JorgeArreolaS @zaerald Sorry for barging in like that but I had similar issues in the past with getting types on filtered arrays and I thought I would take this opportunity to share my solution. 

We can use user-defined type guards or [user type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) to keep the typing accurate while using `array.filter`. IMHO, this makes the code a bit more readable than using a typescript flag.

I tried to make an example as simple as possible:

```typescript
  type Address = { street: string };
  type PersonWithOptionalAddress = { name: string; address?: Address };
  type PersonWithRequiredAddress = { name: string; address: Address };

  const people: PersonWithOptionalAddress[] = [
    { name: 'Simon', address: { street: 'nice street' } },
    { name: 'Sarah' },
  ];

  // Will give error
  /** 
   * Type 'PersonWithOptionalAddress[]' is not assignable to type 'PersonWithRequiredAddress[]'.
   * Type 'PersonWithOptionalAddress' is not assignable to type 'PersonWithRequiredAddress'.
   * Property 'address' is optional in type 'PersonWithOptionalAddress' but required in type 'PersonWithRequiredAddress'. 
   **/
  const peopleMaybeAddresses: PersonWithRequiredAddress[] = people.filter(
    (person) => !!person.address,
  );

  // OK
  const peopleWithAddresses: PersonWithRequiredAddress[] = people.filter(
    (person): person is PersonWithRequiredAddress => !!person.address,
  );
```
Reference (a bit outdated): https://www.benmvp.com/blog/filtering-undefined-elements-from-array-typescript/

I think Typescript changed a bit from when I had to implement this "workaround" though. When using `array.filter` and the result is an array of primitive types, it seems that Typescript infers the result properly.

Cheers !

**Comment by rhart92** [comment]
Closing this issue because it seems like it was not having to do with the SDK but just a typescript issue.
