### ISSUE TITLE
Unable to make a formula property in database

### ISSUE THREAD

**Issue by adityataps** [makenotion/notion-sdk-js#157]
Currently I'm creating an application that automates posting my shared grocery receipts with my roommates. In our old implementation, we have a formula that divides the cost of groceries based on fields on that row that are checked off, corresponding to name. 

My expression can be found here:
`"expression": "if(prop(\"Will\"), prop(\"Total Price\") * 1.07 / ((prop(\"xxx\") ? 1 : 0) + (prop(\"xxx\") ? 1 : 0) + (prop(\"xxx\") ? 1 : 0) + (prop(\"xxx\") ? 1 : 0)), 0)"`

But when I try making a database using the syntax found in documentation as well as in api-types.d.ts as such:

`"Total - Will": {
                        "formula": {
                            "expression": "if(prop(\"xxx\"), prop(\"Total Price\") * 1.07 / ((prop(\"xxx\") ? 1 : 0) + (prop(\"xxx\") ? 1 : 0) + (prop(\"xxx\") ? 1 : 0) + (prop(\"xxx\") ? 1 : 0)), 0)"
                        },
                    },`

I see this:

`@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation. Fix one: body.properties.Total - Will.title should be defined, instead was `undefined`. body.properties.Total - Will.rich_text
 should be defined, instead was `undefined`. body.properties.Total - Will.formula should be not present, instead was `{}`. body.properties.Total - Will.url should
 be defined, instead was `undefined`. body.properties.Total - Will.select should be defined, instead was `undefined`. body.properties.Total - Will.multi_select sh
ould be defined, instead was `undefined`. body.properties.Total - Will.people should be defined, instead was `undefined`. body.properties.Total - Will.files shoul
d be defined, instead was `undefined`. body.properties.Total - Will.email should be defined, instead was `undefined`. body.properties.Total - Will.phone_number sh
ould be defined, instead was `undefined`. body.properties.Total - Will.date should be defined, instead was `undefined`. body.properties.Total - Will.checkbox shou
ld be defined, instead was `undefined`. body.properties.Total - Will.created_by should be defined, instead was `undefined`. body.properties.Total - Will.created_t
ime should be defined, instead was `undefined`. body.properties.Total - Will.last_edited_by should be defined, instead was `undefined`. body.properties.Total - Wi
ll.last_edited_time should be defined, instead was `undefined`.'
}
`

Is my syntax incorrect or is this a possible bug?

**Comment by alfonsodlopez** [comment]
Formulas are not supported as one of the properties that can be created in a database using the current version of the API: 

https://developers.notion.com/reference/create-a-database#database-properties
