### ISSUE TITLE
URL type is mentioned as string but api expects null or non-empty string

### ISSUE THREAD

**Issue by GorvGoyl** [makenotion/notion-sdk-js#160]
URL is of type string but api expects null or non-empty string.
```
export interface URLPropertyValue extends PropertyValueBase {
    type: "url";
    url: string;
}
```

error when passing empty string (see at last):
```
'body failed validation. Fix one: body.properties.Name.id should be defined, instead was `undefined`. body.properties.Name.name should be defined, instead was `undefined`. body.properties.Name.start should be defined, instead was `undefined`. body.properties.Meeting Link.url should be an array, a number, `null`, populated, an object, or a boolean, instead was `""`.'
```
**To Reproduce**
Node version: 14
Notion JS library version: 0.2.3

**Comment by almawang** [comment]
This is expected behavior. The API does not [support empty strings](https://developers.notion.com/reference/intro#json-conventions); instead `null` should be used to clear a property value.
