### ISSUE TITLE
Get Icon and Cover of page.

### ISSUE THREAD

**Issue by ngmiduc** [makenotion/notion-sdk-js#163]
I have a problem when I want to get information from my DB or from the pages.
I kind of miss the cover URL and the Icon URL of my pages.

Is this missing in the API ?

**Comment by perotem7** [comment]
<img width="878" alt="Screen Shot 2021-08-03 at 8 25 36" src="https://user-images.githubusercontent.com/16794186/127962493-bdc7e6f7-5dab-4ccf-bc25-048a9bb268b1.png">

**Comment by alfonsodlopez** [comment]
@ngmiduc, correct. As @perotem7 shows in the screenshot, there the page cover and icon are currently not supported in the API.
