### ISSUE TITLE
Is it possible add a column to the database after it was created?

### ISSUE THREAD

**Issue by tbntdima** [makenotion/notion-sdk-js#169]
Hello, I got stuck in the following use case.

Imagine I've created a database with `Title` and `Description` columns.
Later I realized I want to add a new column `Subtitle`.
Is it possible? 

I've tried to create a new database page with an extra column, but got the following error:
```
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'Subtitle is not a property that exists.'
}
```

**Comment by almawang** [comment]
Yes! See the documentation in [Update Database](https://developers.notion.com/reference/update-a-database)
