### ISSUE TITLE
Incorrect type: `DatabasesRetrieveParameters`

### ISSUE THREAD

**Issue by JFrankfurt** [makenotion/notion-sdk-js#171]
current type:
```
interface DatabasesRetrievePathParameters {
    database_id: string;
}
interface DatabasesRetrieveQueryParameters {
}
interface DatabasesRetrieveBodyParameters {
}
export interface DatabasesRetrieveParameters extends DatabasesRetrievePathParameters, DatabasesRetrieveQueryParameters, DatabasesRetrieveBodyParameters {
}
```

This interface indicates that the only valid parameter for `notion.databases.retrieve` is `database_id`

That doesn't seem to actually be the case, since the docs demonstrate other usage, and the code in the docs functions as expected: https://developers.notion.com/docs/working-with-databases#finding-pages-in-a-database

error if you use the docs demo code:
```
Argument of type '{ database_id: string; filter: { property: string; date: { past_week: {}; }; }; }' is not assignable to parameter of type 'WithAuth<DatabasesRetrieveParameters>'.
  Object literal may only specify known properties, and 'filter' does not exist in type 'WithAuth<DatabasesRetrieveParameters>'.ts(2345)
(property) filter: {
    property: string;
    date: {
        past_week: {};
    };
}

```

**Comment by almawang** [comment]
This method specifically refers to the [Retrieve a database](https://developers.notion.com/reference/retrieve-a-database) endpoint which only has a `database_id` parameter.
