### ISSUE TITLE
Wrong rollup value

### ISSUE THREAD

**Issue by ivanturianytsia** [makenotion/notion-sdk-js#175]
Hi, I am building a [small project](https://github.com/ivanturianytsia/notion-telegram-bookmark) with Notion API for bookmarking pages and ran into an issue with rollups.

**The Issue**
When I'm pulling a database record, it appears to have a wrongly calculated rollup value. It's a max value of a relation to another table that's calculated with a formula. I am also seeing less objects in relation field than it should be. It seems like there's some kind of limiting happening that affects the rollup value calculation. Similar behaviour for other pages, also when changing other values, e.g. doubling the total pages, it divides the wrongly calculated progress value by 2.

Is there anything I can do to fix that?

Thanks.

**API response**
- Value: 50
- Sessions count: 15
<img width="540" alt="Screenshot 2021-08-18 at 19 55 16" src="https://user-images.githubusercontent.com/13473024/129948116-394fd2f2-ee81-430e-b318-7e18223ce7fa.png">

**Notion UI**
- Value: 56
- Sessions count: 18
<img width="704" alt="Screenshot 2021-08-18 at 19 56 30" src="https://user-images.githubusercontent.com/13473024/129948376-911f0a5c-0b20-48a4-8278-03d6fc7de14c.png">

**To Reproduce**
Node version: 12.18.3
Notion JS library version: 0.2.3

**Comment by almawang** [comment]
Thanks for the report! Closing because this isn't an issue with the SDK, however, you can submit bugs and feature requests through Intercom by going to https://developers.notion.com/ and clicking "Help" in the footer.
