### ISSUE TITLE
I want to link GitHub releases with npm js releases.  

### ISSUE THREAD

**Issue by 75asa** [makenotion/notion-sdk-js#179]
**Describe the feature**
npm releases are not automated. Ref #178.

**Expected behavior**
- [ ] add ci to publish npm

**Additional context**
FYI: [Publishing Node.js packages](https://docs.github.com/en/actions/guides/publishing-nodejs-packages#example-workflow)

**Comment by cwang314** [comment]
Hi @75asa , thanks for the feedback! I've gone ahead and added this to our internal tracker and it's definitely on our radar as we ship new types and features for the public API.

We don’t actively monitor the issues in this repo, but you can submit any additional feedback by emailing us at developers@makenotion.com.
