### ISSUE TITLE
Block type issue.

### ISSUE THREAD

**Issue by diamantdev** [makenotion/notion-sdk-js#189]
**Describe the bug**
When we try to create a page, in the childrens, the blocks needs an ID, a created time and updated time, but since we create blocs, we don't have this infos.
 
**To Reproduce**
```typescript
const response = await notion.pages.create({
    parent: {...},
    properties: {...}
    children: [
      {
        object: 'block',
        type: 'embed',
        embed: {
          url: feed.link,
        },
      },
    ],
  });
```

Node version: 16
Notion JS library version: 0.3.2

**Expected behavior**
Well, I think Block type need a little refresh.

**Comment by diamantdev** [comment]
One way to avoid this is to edit the [`api-endpoints.ts`](https://github.com/makenotion/notion-sdk-js/blob/main/src/api-endpoints.ts) file with that:

```typescript
export interface BlockBase {
  object: 'block';
  id?: string;
  type: string;
  created_time?: string;
  last_edited_time?: string;
  has_children?: boolean;
}
```

But idk if this will the good solution to all the API.

**Comment by AsishRaju** [comment]
> One way to avoid this is to edit the [`api-types.ts`](https://github.com/makenotion/notion-sdk-js/blob/main/src/api-types.ts) file with that:
> 
> ```ts
> export interface BlockBase {
>   object: 'block';
>   id?: string;
>   type: string;
>   created_time?: string;
>   last_edited_time?: string;
>   has_children?: boolean;
> }
> ```
> 
> But idk if this will the good solution to all the API.

This would only work in local work env, pushing this to any prod env where your node modules are pulled from npm this would fail

**Comment by nartc** [comment]
@AsishRaju if you're still stuck on this, here's a workaround.

Since `BlockBase` is an interface, you can utilize [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). In your codebase, have a `typings.d.ts` (or any name you like and make sure your `tsconfig` is aware this file. For my case, `tsconfig` knows all `d.ts` files in my root).

```ts
// typings.d.ts
declare module "@notionhq/client/build/src/api-types" {
   export interface BlockBase {
      id?: string;
      created_time?: string;
      last_edited_time?: string;
   }
}
```

**Comment by rhart92** [comment]
As the types are now auto-generated from our source code, this issue is out of date. Please update to the latest version for improved typings.
