### ISSUE TITLE
NOTION_DATABASE_ID is object_not_found

### ISSUE THREAD

**Issue by akarabach** [makenotion/notion-sdk-js#194]
I have duplicated notion template and set up .env using my keys and ids. But, I always receive object_not_found, I've tried ids from my URI for notion duplicated template (both which before `?v=` and after `?v=`)

**Comment by tianheg** [comment]
Share the Database with your intergration

**Comment by idkjs** [comment]
What is the integration set up for https://github.com/makenotion/notion-sdk-js/tree/main/examples/database-email-update? I dont see it in the docs?

**Comment by tianheg** [comment]
Maybe you want [this](https://developers.notion.com/docs/getting-started#step-2-share-a-database-with-your-integration)

**Comment by idkjs** [comment]
@tianheg thank you, madame/sir.
