### ISSUE TITLE
Code block doesn't parse after 10000bytes characters.

### ISSUE THREAD

**Issue by nightohl** [makenotion/notion-sdk-js#202]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@notion.com.

**Describe the bug**
Code block doesn't parse after 10000bytes characters.

**Screenshots**
Until 9999bytes input, 'Code block' parse the syntax well. but If write more than 9999 letters, doesn't parse it.
![image](https://user-images.githubusercontent.com/48432932/135566688-44d6135b-679d-4f5d-8c98-64da00133a9a.png)

**Additional context**
I'd like to patch the source code, but It seems not a part of `notion-sdk-js`, so I just report it. Thanks.

**Comment by rhart92** [comment]
@nightohl, currently this is a limitation in the Notion product and unrelated to the API. I have noted your feedback internally so it can be tracked. Closing this issue for now.
