### ISSUE TITLE
Page icon and cover stopped showing up with pages API

### ISSUE THREAD

**Issue by mikihau** [makenotion/notion-sdk-js#213]
**Describe the bug**
Today I noticed that page icon and cover properties stops showing up with Retrieve a Page API, and Create/Update API ignores these properties. Could it be a regression?

**To Reproduce**
Just do something like
```
 const response = await notion.databases.query({
    database_id: "my database id"
  });
console.log(rsponse.results[0]);
```
And I got
```
{
  object: 'page',
  id: '...',
  created_time: '2021-09-19T21:42:00.000Z',
  last_edited_time: '2021-09-25T12:56:00.000Z',
  parent: {
    type: 'database_id',
    database_id: '.....'
  },
  archived: false,
  properties: {
    ...
  },
  url: 'https://www.notion.so/...
}
```
This is from a page that I verified to have a cover from the UI. No `icon` or `cover` properties there!

Node version: v14.17.0
Notion JS library version: 0.4.3

**Expected behavior**
I'm expecting icon and cover to show up from the response as described in the [documentation](https://developers.notion.com/reference/retrieve-a-page):
![Screen Shot 2021-10-11 at 2 15 54 PM](https://user-images.githubusercontent.com/41554553/136856462-60a4531f-03f3-4ad5-99d6-d327c21a072f.png)

**Additional context**
I'm sure it used to work two weeks ago, so I'm suspecting a regression in either API itself, or the sdk.

**Comment by flaviocopes** [comment]
Would be cool if `icon` and `cover` were also showing for `child_page` blocks (subpages) we get through `notion.blocks.children.list()`. 

As a workaround now I can detect a block is `child_page` and then call `notion.pages.retrieve({ page_id: ... })`, but it's one more API call for each subpage
