### ISSUE TITLE
Separate input and output types

### ISSUE THREAD

**Issue by aoberoi** [makenotion/notion-sdk-js#22]
from #20 

> Another shortcoming is that there isn't a good separation between "input" types and "output" types. This matters in situations where a method accepts, for example, a Block in its parameters. At call time, a block won't have properties like id - those are assigned by the server. However, the Block type has id set as a non-optional property. This is a real issue and should be handled in a bugfix.

**Comment by ooloth** [comment]
Thanks for identifying this! It will be nice for TS to let us omit properties we aren't updating from their default values when sending `POST` requests, as described here:

> typescript forces all the properties id, title, that's why i have created that createTitle()
cause all TitlePropertyValue properties are required

https://github.com/makenotion/notion-sdk-js/discussions/45#discussioncomment-738035

**Comment by rhart92** [comment]
Auto-generated types should resolve this issue as we now have `input` and `output` type distinctions.
