### ISSUE TITLE
Cannot create root pages

### ISSUE THREAD

**Issue by remorses** [makenotion/notion-sdk-js#240]
**Describe the bug**
Trying to create a root page (no `parent` `page_id` or `database_id`) will always result in an error

**To Reproduce**
Node version: 14
Notion JS library version: 

All the following snippets will fail with ```body failed validation. Fix one: body.parent.database_id should be defined, instead was `undefined`. body.parent.page_id should be defined, instead was `undefined`.```
```ts
import { Client } from '@notionhq/client'

const NOTION_TOKEN = process.env.NOTION_TOKEN

const notion = new Client({
    auth: NOTION_TOKEN,
})

notion.pages.create({
    parent: {
        workspace: true,
        type: 'workspace',
    },
    children: [],
    properties: {
        title: { title: [{ text: { content: 'title' } }] },
    },
})

```

```ts
import { Client } from '@notionhq/client'

const NOTION_TOKEN = process.env.NOTION_TOKEN

const notion = new Client({
    auth: NOTION_TOKEN,
})

notion.pages.create({
    children: [],
    properties: {
        title: { title: [{ text: { content: 'title' } }] },
    },
})

```

**Expected behavior**
There should be a way to create a root page

**Screenshots**

**Additional context**

**Comment by remorses** [comment]
This is probably because I am using an Internal Integration? i found that with internal integration you have to manually share pages with the integration to be able to update them.

**Comment by rhart92** [comment]
Currently, we don't allow you to create top-level pages with the public API. What use-case are you trying to accomplish that requires top-level page creation?

**Comment by remorses** [comment]
I am creating a converter from [Gitbook](https://www.gitbook.com/) to Notion

**Comment by rhart92** [comment]
Thanks for sharing! One options is you could have the top level page be something like "Product Docs" and the integration can be granted access to this page which you can create the docs inside that page. Normally a Notion workspace will be used for many things so it seems like it makes sense that the docs would not be the whole workspace 🤔 I'm going to close this issue, but I have noted the feedback in our internal tracker 🙏

**Comment by CaptainYouz** [comment]
Thanks for the tip @rhart92 .
I have a use case where i want to create, through an API subpages/sub-databases, through the public API.
When the user authenticate with OAuth, he give permissions to read/update/write on a specific page. 
However, how can I retrieve (through Notion API) this page so i can use it's id to create new subpages?
