### ISSUE TITLE
Toggles that have headings do not show up as toggles in response

### ISSUE THREAD

**Issue by aalemayhu** [makenotion/notion-sdk-js#245]
Hei there,

I am using the API to help people create Anki flashcards faster on 2anki.net. We are heavy users of toggle lists but currently rely on the manual HTML export. We hope to transition to using the API soon. While doing some regression testing with the API (client v0.4.11), I discovered some toggle lists were missing. 

**Describe the bug**
When using headings in the toggle list summary, the API response does not include the toggle list but instead marks it as a heading.  See attached screenshot and JSON payload.

**To Reproduce**
Node version: v16.13.0
Notion JS library version: v0.4.11

1. Create a toggle list with heading 1 in the summary
2. Retrieve the blocks 

**Expected behavior**
I was expecting the toggle lists to remain a toggle list regardless of it having headings or not in the summary.

**Screenshots**
In the screenshot below, the two top toggles are not type `toggle` but show up as type `heading_1`
<img width="800" alt="Screenshot 2021-12-23 at 1 02 28 PM" src="https://user-images.githubusercontent.com/925044/147239128-abb7566c-8367-4897-9fc4-170550e7f622.png">

**Additional context**
Attached is the JSON response for this page https://alemayhu.notion.site/All-Articles-Why-You-Should-Compete-in-a-Saturated-Market-BusinessCollective-ea9a40bdf740443fb81a2ad3eb29f4fe

[blocks.children.list.json.txt](https://github.com/makenotion/notion-sdk-js/files/7769243/blocks.children.list.json.txt)
[blocks.retrieve.json.txt](https://github.com/makenotion/notion-sdk-js/files/7769244/blocks.retrieve.json.txt)

**Comment by cwang314** [comment]
Hi @aalemayhu, thanks for the report; I've added this to our internal tracker. I'm closing this issue because we want the issues in this github repo to be SDK-specific. However, you can always submit bugs and feature requests for the API through Intercom by going to [https://developers.notion.com/ and](https://developers.notion.com/%C2%A0and) clicking "Help" in the footer.
