### ISSUE TITLE
Frontend Interactions from Integrations/API?

### ISSUE THREAD

**Issue by ndbeals** [makenotion/notion-sdk-js#255]
Hello, as the title states, is it possible to interact with the frontend/client DOM from the API?

E.G embedding an iframe of custom content, such as generating a visualization from data in a database using D3.js

I know the "embed" type exists, I was unable to find any documentation on it on the API references though. Thanks

**Comment by almawang** [comment]
Hi @ndbeals, it is not possible to interact with frontend/client DOM via the API. I would recommend using the Notion Devs Slack for these types of questions.
