### ISSUE TITLE
Not applying the formatting from the source I copy pasted in my note

### ISSUE THREAD

**Issue by ashwani-zomato** [makenotion/notion-sdk-js#256]
If I cop coloured paragraph and headings from a source and paste it in notion noteboook, it only keeps then in default black color.
Please help. I want them to be exactly the same color.

**Comment by rhart92** [comment]
Thanks for confirming @ashwani-zomato. Please feel free to file a ticket with Notion support using intercom (see screenshot below for how to do this) but this is for issues related to the Notion JS SDK, therefore closing this issue.
<img width="259" alt="CleanShot 2022-02-07 at 09 30 40@2x" src="https://user-images.githubusercontent.com/3171522/152840733-aef44175-e722-4282-839b-5c27c2043bce.png">

**Comment by ashwani-zomato** [comment]
thanks a lot @rhart92 
kudos to you and your team for this awesome product.
i like the hierarchy of notes feature a lot ❤️
