### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by AA0000-33** [makenotion/notion-sdk-js#257]
**Describe the bug**
Notion should have support for RTL languages like Arabic where the text is Right to Left, instead of LTR.

**To Reproduce**
Node version: latest
Notion JS library version: latest

Write anything in Arabic

**Expected behavior**
Text should appear on the right of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/22997509/153388682-bbb7bc5f-f015-46d0-ad44-6f5fa80cf787.png)

**Comment by almawang** [comment]
Closing this since not related to API or SDK. I'd recommend looking at the [Notion Help Page](https://www.notion.so/help) for assistance on the Notion product.
