### ISSUE TITLE
How subscribing to updates

### ISSUE THREAD

**Issue by Dekhnar** [makenotion/notion-sdk-js#258]
How can I watch updates on my datatable like notion does with 
wss://msgstore.www.notion.so/primus ? Any plan to do so?

**Comment by Dekhnar** [comment]
Any news?

**Comment by cwang314** [comment]
@Dekhnar currently the recommended way is to poll the relevant database using the [query database endpoint](https://developers.notion.com/reference/post-database-query).

We're trying to keep the issues in this github repo specific to the SDK itself, so I'm closing this issue. For feature requests and bug reports, you can email developers@makenotion.com; or to get help from the community you can join [Notion Devs slack](https://join.slack.com/t/notiondevs/shared_invite/zt-vkinpzs0-hJSEAAxJzPMuiCNvZETF2A).
