### ISSUE TITLE
QueryDatabaseResponse type breaking when `created_by` is returned from API

### ISSUE THREAD

**Issue by anhari** [makenotion/notion-sdk-js#260]
**Describe the bug**
`QueryDatabaseResponse` doesn't account for `created_by` property.

**To Reproduce**
Node version: 17.4.0
Notion JS library version: 0.4.13

Query a database and get back a response with `created_by` in the `results` key.

**Expected behavior**
The `QueryDatabaseResponse` type should work with all responses from querying a database.

**Screenshots**
![created_by_type_error](https://user-images.githubusercontent.com/6628875/154821355-04e93aa1-8642-401c-aa7a-be98669fe583.png)

**Comment by cwang314** [comment]
@anhari thanks for reporting! This should be fixed with the newest version, `1.0.1`.
