### ISSUE TITLE
Adding user mention stopped working in Notion API

### ISSUE THREAD

**Issue by bahriddin** [makenotion/notion-sdk-js#261]
**Describe the bug**

Looks like adding mention to the block with API is not working as before.

**To Reproduce**
Node version: v16.13.0
Notion JS library version: 0.4.13

I was adding user mention in the block with the following simple algorithm:
- Get all person users in the Notion
- Find a user where name == given name
- If not empty add some text with user mention at the end. Here I provided found user:

```JS
const parentId = 'SOME_HASH_ID_HERE';
const message = { content: 'TEXT', author: getNotionUser("John Doe")};

if(message.author != undefined) {
  appendToBlock(parentId, message);
}

async function appendToBlock(blockId, message) {
  return await notion.request({
    path: `blocks/${blockId}/children`,
    method: 'PATCH',
    body: bulletedList(message),
  });
}

function bulletedList(message) {
  return {
    children: [
      {
        object: 'block',
        type: 'bulleted_list_item',
        bulleted_list_item: {
          text: [
            {
              type: 'text',
              text: {
                content: message.content + ' ',
              },
            },
            {
              type: 'mention',
              mention: {type: 'user', user: message.author},
            },
          ],
        },
      },
    ],
  };
}

async function getNotionUser(userName) {
  const notionUsers = (await notion.users.list()).results.filter(item => {
    return item.type === 'person';
  });
  return notionUsers.find(notionUser => notionUser.name === userName);
}
```
It was working fine until 2 days ago but now getting this error:
```
{
  "object":"error",
  "status":400,
  "code":"validation_error",
  "message":"Content creation Failed. Fix the following: 
   Could not find user with ID: c95###################26."
}
```

**Expected behavior**
It should post a block mentioning user.

**Comment by cwang314** [comment]
@bahriddin this should be fixed now, can you try again?

**Comment by cwang314** [comment]
Closing this issue because we want to keep the issues in this repo specific to the SDK itself (rather than the API's behavior). If you continue to encounter problems, you can email us at developers@makenotion.com which is where we triage and process most of our bug reports.

**Comment by bahriddin** [comment]
Thanks for the response @cwang314. I ended up writing user name as a simple text and it looks better solution than mentioning in my case.
I will email in future.
Cheers
