### ISSUE TITLE
Deleting multiple blocks at once leads to conflict error that cant be caught

### ISSUE THREAD

**Issue by danielannan17** [makenotion/notion-sdk-js#265]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
When you do notion.blocks.delete to delete multiple blocks at the same time or in quick succession, it leads to a conflict error which cant be caught by try-catch block (as in the example) nor a promise.catch function.

```
@notionhq/client warn: request fail {
  code: 'conflict_error',
  message: 'Conflict occurred while saving. Please try again.'
}
node_modules\@notionhq\client\build\src\errors.js:162
        return new APIResponseError({
               ^
```

```
APIResponseError: Conflict occurred while saving. Please try again.
    at buildRequestError (node_modules\@notionhq\client\build\src\errors.js:162:16)
    at Client.request (node_modules\@notionhq\client\build\src\Client.js:304:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async notion.js:132:13
    at async Promise.all (index 3)
    at async notion.js:129:7
    at async Promise.all (index 3)
  code: 'conflict_error',
  status: 409,
```

  `body: '{"object":"error","status":409,"code":"conflict_error","message":"Conflict occurred while saving. Please try again."}'`

**To Reproduce**
Node version: v16.14.0
Notion JS library version: @notionhq/client": "1.0.0"

Delete multiple (at least 5?) blocks at the same in a loop ( May take a few tries)

```
blocks.map(async (block, index) => {
          if (block.type == 'to_do') {
            try {
              await notion.blocks.delete({
                block_id: block.id,
              })
            } catch(e) {
              console.log("Didnt catch here")
            }
          }
        })
```

```
blocks.map(async (block, index) => {
          if (block.type == 'to_do') {
            await notion.blocks.delete({
              block_id: block.id,
            }).catch(error => {
              console.log("Didnt catch here")
            })
          }
        })
```

**Expected behavior**
Not to get an error or at least be able to catch the errors to try again.

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by Antisunny** [comment]
don't use `.map()`, `await` doesn't wait in `.map()`. 

use `for (of) { await }` instead.

**Comment by rhart92** [comment]
Issuing many simultaneous delete requests will result in conflicts. Based on your issue, it seems like you are just looking for a way to determine which blocks errors so you can try again. In this case, you can continue to use `map` but handle the errors using something like `Promise.allSettled` which will allow determining which promises succeeded and which need to be tried again. See the code example below:

```ts
// Setup Notion client...

// Fetch all the blocks on a page
const response = await client.blocks.children.list({
block_id: "663fb591f06e41e38c86228756bb5ff0"
})

// Map blocks to delete request promises.
const deletePromises = response.results.map(result => 
  client.blocks.delete({
	  block_id: result.id
  })
)

// Use new `Promise.allSettled` to get
const promiseResults = await Promise.allSettled(deletePromises)
// promiseResults will contain an array of objects with a status property that
// will allow you to determine which results succeeded and which failed. See
// more details in the docs 👇
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled
```

If the goal is to avoid conflicts entirely, issuing delete requests synchronously and handling errors for each block would be your best bet (which can be achieved by not using `map` like @Antisunny suggested).

Since this isn't an issue with the SDK I'm going to close this issue 🙏

**Comment by xiaobili** [comment]
using recursion can solve this problem well. Here is my code.

```javascript
  const arrs = resp.results.filter(
    (item) => item.type === "code" && item.code.language != "java"
  );

  const runner = async (item) => {
    const r = await notion.blocks.update({
      block_id: item.id,
      code: {
        language: "java",
      },
    });
    if (r && arrs.length > 0) {
      console.log("update", item.id);
      runner(arrs.pop());
    }
  };

  await runner(arrs.pop());
```
