### ISSUE TITLE
Inconstancy between types and actual data for `@1.0.0`. 

### ISSUE THREAD

**Issue by iheyunfei** [makenotion/notion-sdk-js#266]
**Describe the bug**
As I already commented on https://github.com/makenotion/notion-sdk-js/pull/262#issuecomment-1054057010.

I found the actual structure the SDK returned is still { text: Array<RichTextItemResponse> }. Is this expected?

**To Reproduce**
Node version:
Notion JS library version:

**Expected behavior**

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by iheyunfei** [comment]
I guess that's why. The right version for current types is `2022-02-22`.

https://github.com/makenotion/notion-sdk-js/blob/871d04c8cbc1c5de4cf6f8a93d4e1fb59b32f4f5/src/Client.ts#L109

https://developers.notion.com/changelog/releasing-notion-version-2022-02-22

**Comment by iheyunfei** [comment]
For anyone who meets this problem. There's workaround
```ts
  new Client({
    notionVersion: '2022-02-22',
    auth: process.env.NOTION_TOKEN!,
  }),
```

**Comment by Vispercept** [comment]
Thanks @iheyunfei. That really helped me out!
