### ISSUE TITLE
Mermaid node cannot display two lines correctly 

### ISSUE THREAD

**Issue by vallettea** [makenotion/notion-sdk-js#279]
When you try to put text node on two lines, the second line appears only partially. 
For example if you take the working behavior of [this issue](https://stackoverflow.com/questions/51366763/mermaid-diagram-line-break) and put it in notion you see the last node has the pb
```
graph TB
        A[GE Solution]-->C{ }
        B[GA Solution]-->C{ } 
        C{ }-->D[Stir 10 mins at 500 r/min]
        D[Stir 10 mins at 500 r/min]-->E[Homogenisation at 10000 r/min]
        E[Homogenisation at 10000 r/min]-->F(Stir 10 min 450 r/min <br> Complex  coacervation)
```

**Screenshots**
<img width="676" alt="Capture d’écran 2022-03-23 à 18 59 49" src="https://user-images.githubusercontent.com/371303/159765786-74cfe2a1-6d0c-42ed-848e-a13d90ad1d82.png">

**Additional context**
I'm sure it is because of the css class "nodeLabel" that is used both by notion and mermaid

**Comment by rhart92** [comment]
Thanks @vallettea for the report about the mermaid renderer. Unfortunately, this is only used for reporting issues with the Notion API JS SDK. I'll file the bug for you internally and close this issue.

**Comment by jurajpiar** [comment]
[rhart92](https://github.com/rhart92) could you please advise us as to where we can report issues?
I found this one as I have a similar issue with mermaid renders. Every node text is cut-off to the right, so far in any type of mermaid diagram.

Btw, when I press the "message support" button in the electron app, nothing happens, either.
