### ISSUE TITLE
Hope the official development team will release a blog framework

### ISSUE THREAD

**Issue by allinu** [makenotion/notion-sdk-js#281]
# This is not a BUG report.

The purpose of this SDK development should be to help users use it better, and it is more convenient to expand functions. As a simple user, I will not use this SDK for development, and I cannot use JS very well. I strongly need one that can be used directly. A framework that allows us to deploy directly on our own server is the best, just like [this project](https://github.com/transitive-bullshit/nextjs-notion-starter-kit),but [this project](https://github.com/transitive-bullshit/nextjs-notion-starter-kit), But this project is not updated in time, nor is it an official project.

I think that if we use this to build a framework, our original data in the application will not be affected, it will also facilitate the expansion of functions, optimize the display, and at the same time, it will improve the views of some people on the application and attract more users to the application.

I am asking questions here, mainly because I hope that the official or capable people can help us. We all hope that this application will become better and better. After all, a lot of data is on it.

With my highest respect.

**Comment by transitive-bullshit** [comment]
I agree that this is an important use case that the Notion team should consider.

In the meantime, you may want to check out our compatibility layer between the official Notion API and the private API: https://github.com/NotionX/react-notion-x/pull/256

**Comment by cwang314** [comment]
@allinu thanks for starting this discussion. It's not currently on the API team's roadmap to build out a framework for supporting blogging - we're more immediately focused on improving and enhancing the API, as opposed to building out the scaffolding around it for specific use cases.

We haven't been actively monitoring the issues in this repo, but you can submit any feature requests by emailing us at developers@makenotion.com.
