### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by Achder** [makenotion/notion-sdk-js#284]
Hi, 
we wrote a client application, that polls the notion api every second. Sometimes we get 

```
Client warn: request fail {
  code: 'rate_limited',
  message: 'You have been rate limited. Please try again in a few minutes.'
}
```

I can't find anything about read rate limits. Can somebody tell me what those are?

**Comment by mattcasey** [comment]
https://developers.notion.com/reference/request-limits
> The rate limit for incoming requests is an average of 3 requests per second. Some bursts beyond the average rate are allowed.

**Comment by rhart92** [comment]
Thanks @mattcasey for providing the link to the rating limiting documentation 🙏 Closing this issue for now since it seems like that was all @Achder was looking for.
