### ISSUE TITLE
mismatch typing to api response

### ISSUE THREAD

**Issue by waptik** [makenotion/notion-sdk-js#285]
**Describe the bug**
So I am using this library to interact with the API, but the type definitions are buggy as some responses don't match what to expect according to API reference. As you can see in the screenshot below, I only get three object keys for a single database object after using the result from the search api.

**To Reproduce**
Node version: v16.13.0
Notion JS library version: 1.0.4

```
import { Client as notionClient } from "@notionhq/client";
.....
const notion = notionClient({ auth: user.token });
const response = await notion.search({ filter: { property: "object", value: "database" }});
const results = response.results 

if (results && results .length > 0) {
		results.map(base => {
			if (base.object === 'database') {
				base // see screenshot below for prediction
			}
		})
	}
....
```

**Expected behavior**
I should have access to all object keys for a database object as mentioned in https://developers.notion.com/reference/database#all-databases.

**Screenshots**
![image](https://user-images.githubusercontent.com/1687551/162647619-c3ab8ac8-f37a-4ddd-8634-2db17b42967c.png)

**Comment by waptik** [comment]
I think I figured it out by myself(https://twitter.com/_waptik/status/1521212734381203458). It would be great if there were documentation indicating how to access objects from responses.

**Comment by btvoidx** [comment]
Thank you for your finding!
