### ISSUE TITLE
Not clear how to create toggle headings via the API

### ISSUE THREAD

**Issue by dmitry-weirdo** [makenotion/notion-sdk-js#295]
I want to create the toggle headings 1-3 via the Notion API. However, I cannot find the distinction between normal headers and toggle headers in the API.

https://developers.notion.com/reference/block#heading-one-blocks — this doc only lists "type": "heading_1" without any additional properties to distinguish the toggle header from the normal (non-toggle) header.

When I get the toggle header block via API, I also cannot see any properties that indicate that the header is a toggle heading.

I've tried to create a heading one with explicitly setting the `has_children: true`, but it does not create a toggle header.

However, appending to the existing toggle heading is working.

My question on SO: https://stackoverflow.com/questions/72076506/how-to-retrieve-and-create-the-toggle-heading-blocks

**Comment by dmitry-weirdo** [comment]
Seems to work via the pure API with passing the children to the heading block:

```bash
curl -X PATCH 'https://api.notion.com/v1/blocks/YOUR_PAGE_ID/children' \
  -H 'Authorization: Bearer '"$NOTION_API_KEY"'' \
  -H "Content-Type: application/json" \
  -H "Notion-Version: 2022-02-22" \
  --data '{
  "children": [
    {
      "object": "block",
      "type": "heading_1",
      "heading_1": {
        "rich_text": [{ "type": "text", "text": { "content": "Heading 1 from script (try 2)" } }],
        "children": [
          {
            "object": "block",
            "type": "paragraph",
            "paragraph": {
              "rich_text": [
                {
                  "type": "text",
                  "text": {
                    "content": "Lacinato kale is a variety of kale with a long tradition in Italian cuisine, especially that of Tuscany. It is also known as Tuscan kale, Italian kale, dinosaur kale, kale, flat back kale, palm tree kale, or black Tuscan palm.",
                    "link": { "url": "https://en.wikipedia.org/wiki/Lacinato_kale" }
                  }
                }
              ]
            }
          }
        ]
      }
    }
  ]
}'
```

It's just my used JVM library that does not support adding the children for the Heading1-3 blocks.

I've created an issue there — see https://github.com/seratch/notion-sdk-jvm/issues/45.

**Comment by rhart92** [comment]
Thanks for the report that our API documentation isn't clear about handling toggle headers. I have filed an internal task to update the documentation. Closing this issue since the SDK does support creating toggle headers by adding the `children` property as you pointed out.
