### ISSUE TITLE
"Update page" API cannot set "parent" prop

### ISSUE THREAD

**Issue by Lluvia95** [makenotion/notion-sdk-js#297]
I cannot move any page to new location, if I copy all the props to a new page which inside the destination page or database, I have to update all the mentions to the old page... even I want to do this, Notion API has no method to get "linked to page" prop...

So please give me a way to move pages. Many thanks!

**Comment by rhart92** [comment]
Thanks for the enhancement request 🙏 I will add "moving page" to our internal feature tracker. For now, closing this issue since it's not specifically an issue with the JS SDK.

**Comment by arunsathiya** [comment]
I just wanted to echo my interest for this feature request as well. I'm currently creating pages in a database, but when certain conditions are met, I want to move that page to the root folder. Currently the update endpoint does not support that functionality. So plus one for the feature request.

**Comment by arunsathiya** [comment]
In fact, [it looks like a new page cannot be created at the root level either](https://github.com/makenotion/notion-sdk-js/issues/240). So, I think the update API endpoint having support for moving a page to the root level would first require the create endpoint to have support for creating pages at the root level. Is my understanding correct here?
