### ISSUE TITLE
Getting "APIResponseError: Unsaved transactions: runQuery" 

### ISSUE THREAD

**Issue by aseem-thakar** [makenotion/notion-sdk-js#298]
**Describe the bug**
I'm trying to create a page in Notion with a bunch of children. I've checked that none of the parameters exceed the request limits for property values specified [here](https://developers.notion.com/reference/request-limits)

```
await notionClient.pages.create({
    parent: {
      database_id: notionLibraryDbId,
    },
    icon: {
      type: "emoji",
      emoji: "🧵",
    },
    properties: {
      Name: {
        title: [
          {
            text: {
              content: fullThreadText[0].text.slice(0, 50) + "...",
            },
          },
        ],
      },
      Type: {
        multi_select: [
          {
            name: "🧵Thread",
          },
        ],
      },
      URL: {
        url: threadUrl,
      },
    },
    children: threadTextInNotionParagraphs,
  });
```

But I receive this error in response:

```
APIResponseError: Unsaved transactions: runQuery
    at buildRequestError (C:\Users\***\server\node_modules\@notionhq\client\src\errors.ts:240:12)
    at Client.request (C:\Users\***\server\node_modules\@notionhq\client\src\Client.ts:178:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'set-cookie': [Array],
      'x-dns-prefetch-control': [Array],
      'x-frame-options': [Array],
      'strict-transport-security': [Array],
      'x-download-options': [Array],
      'x-content-type-options': [Array],
      'x-xss-protection': [Array],
      'referrer-policy': [Array],
      'content-security-policy': [Array],
      'x-content-security-policy': [Array],
      'x-webkit-csp': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'expect-ct': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"Unsaved transactions: runQuery"}'
```

**To Reproduce**
Node version: 14.18.1
Notion JS library version: 1.0.4

**Additional context**
I am calling the API before this to search for a particular page and update it if necessary. I've tried adding a sleep function that waits for 1 second before making every API request  but I still get the same error.

**Comment by rhart92** [comment]
Hi @aseem-thakar. I looked through our logs to attempt to determine the root cause for this issue. Since you didn't provide an exact request body I can't be sure but I found a bunch of errors with the same `runQuery` error that were related to invalid unicode characters in the request body. I have updated the response error message to provide this information. I'm going to close this issue but if you find that you are still having issues, please feel free to re-open the issue and provide a request body that causes the error so we can debug further 🙏
