### ISSUE TITLE
retrieved database object doesn't contain database `description` property

### ISSUE THREAD

**Issue by Antisunny** [makenotion/notion-sdk-js#299]
**Describe the bug**

retrieved database object doesn't contain database `description` rich_text content

**To Reproduce**

Node version: v18.0.0
Notion JS library version: 1.0.4

**Expected behavior**

a property named `description` included in the returned database object.

**Screenshots**
![image](https://user-images.githubusercontent.com/2398514/168420403-886431e2-e952-4c92-ae64-a8fbef5562e1.png)

**Comment by cwang314** [comment]
Hi @Antisunny, thanks for the API feature request; I've gone ahead and added this to our internal tracker. We don’t actively monitor the issues in this repo, but in the future you can submit a feature request by emailing us at developers@makenotion.com.
