### ISSUE TITLE
Property title have an incomplete content

### ISSUE THREAD

**Issue by zavbala** [makenotion/notion-sdk-js#301]
**Describe the bug**
Items from database have an incomplete title

**To Reproduce**
Node version: v18.2.0
Notion JS library version: 1.0.4

**Expected behavior**
That my title have a full content

**Screenshots**
![My Database](https://user-images.githubusercontent.com/95885060/169602933-5e333ab9-bbb9-4e69-b51a-52078dca179b.png)

My output from my code

```JavaScript
const getProducts = async () => {
  const database_id = "";

  const db = await notion.databases.query({
    database_id,
  });

  const records = [];

  for (const iterator of db["results"]) {
    const entry = iterator["properties"];

    const data = {
      Title: entry["Title"].title[0].text.content,
      Price: String(entry["Price"].number),
      Category: entry["Category"].select.name,
      Brand: entry["Brand"].select.name,
      Status: entry["Status"].select.name,
    };

    if (data.Status === "True") records.push(data);
  }

  return records;
};
```

```JavaScript
[
  {
    Title: 'P',
    Price: '550',
    Category: 'Jeans',
    Brand: 'Urban Pipeline',
    Status: 'True'
  },
  {
    Title: 'P',
    Price: '650',
    Category: 'Jeans',
    Brand: 'Magellan',
    Status: 'True'
  },
  {
    Title: 'P',
    Price: '550',
    Category: 'Jeans',
    Brand: 'Magellan',
    Status: 'True'
  },
  {
    Title: 'Pantalón Vestir',
    Price: '550',
    Category: 'Jeans',
    Brand: 'Croft & Barrow',
    Status: 'True'
  },
  {
    Title: 'Pantalón - Corte Bota  - 2 pzas - 32x32',
    Price: '550',
    Category: 'Jeans',
    Brand: 'Urban Pipeline',
    Status: 'True'
  }
]
```

**Comment by cwang314** [comment]
Hi @zavbala , thanks for the bug report. Bugs with the API should be emailed to developers@makenotion.com, not opened as an issue in this repo. As a result I'm closing this issue.

That said, `title` is an array of [rich text objects](https://developers.notion.com/reference/rich-text) and it looks to me like your code is only taking into account the first element of each `title` array. If your page titles happen to contain hyperlinks, mentions, or formatting, those will get truncated by your code. Hope that helps.
