### ISSUE TITLE
Paginated utility functions fail for search

### ISSUE THREAD

**Issue by Kerrick** [makenotion/notion-sdk-js#329]
**Describe the bug**
Paginated utility functions fail for search. This includes both `iteratePaginatedAPI` and `collectPaginatedAPI`.

**To Reproduce**

Node version: v16.15.1

Notion JS library version: 2.1.0

Illustrative code that reproduces the behavior:

```ts
import { Client, collectPaginatedAPI, iteratePaginatedAPI } from '@notionhq/client'

export default class Example {
  private client = new Client({ auth: 'REDACTED', notionVersion: '2022-06-28' })

  public async example() {
    for await (const result of iteratePaginatedAPI(this.client.search, {
      filter: { property: 'object', value: 'page' },
    })) {
      console.log(result)
    }
  }
}
```

**Expected behavior**

I would expect it not to throw an exception, and to instead have the behavior shown in the documentation and when using these utilities with other paginated methods. In the above example, each result should be logged to the console. Instead, the following exception is thrown:

```
TypeError: Cannot read properties of undefined (reading 'request')
    at search (/path/to/node_modules/@notionhq/client/src/Client.ts:511:17)
    at iteratePaginatedAPI (/path/to/node_modules/@notionhq/client/src/helpers.ts:50:49)
    at iteratePaginatedAPI.next (<anonymous>)
    at example.example (/path/to/example.ts)
```

**Comment by lao9** [comment]
Thanks so much for spotting - I believe I found a root cause and will have a fix out today.

**Comment by Kerrick** [comment]
> Thanks so much for spotting

Thanks so much for the utility functions 😁
