### ISSUE TITLE
Bad typings

### ISSUE THREAD

**Issue by polRk** [makenotion/notion-sdk-js#331]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
How can i suggest what type of response i got base on typings? 

```ts
export declare type GetPageResponse = PageObjectResponse | PartialPageObjectResponse;
```

**To Reproduce**
Node version: cloudflare workers
Notion JS library version: "2.1.0"

**Expected behavior**
Return only PageObjectResponse or PartialPageObjectResponse exactly

**Comment by lao9** [comment]
It's possible that a page object may be returned as partial in cases where a page is mentioned outside of the bot's scope or access.

Per our docs: https://developers.notion.com/reference/page

> Properties marked with an * are available to integrations with any capabilities. Other properties require read content capabilities in order to be returned from the Notion API. For more information on integration capabilities, see the [capabilities guide](https://developers.notion.com/reference/capabilities).

As a suggestion, you can narrow the type in `TypeScript` by checking for additional keys that are not in the `PartialPageObjectResponse`. 

Hope that helps.

https://user-images.githubusercontent.com/4068853/181292674-67bdca40-e61e-4e3b-9447-6ad0d0b67ce0.mov

**Comment by lao9** [comment]
Oh! Also we have official helper typeguards now to do a more official check! (e.g. `isFullPage`)

https://github.com/makenotion/notion-sdk-js#typescript

**Comment by polRk** [comment]
@lao9 This is fundamentally wrong. `pages.retrieve` MUST return PageObjectResponse

**Comment by zaragit** [comment]
I also don't understand yet.

```TypeScript
export declare type QueryDatabaseResponse = {
    type: "page";
    page: EmptyObject;
    object: "list";
    next_cursor: string | null;
    has_more: boolean;
    results: Array<PageObjectResponse | PartialPageObjectResponse>; // <- ??
};
```

I don't know why ```PartialPageObjectResponse``` is needed.

```TypeScript
export declare type PageObjectResponse = {
    object: "page";
    id: string;
    parent?: {
        type: "database_id";
        database_id: string;
    } | {
        type: "page_id";
        page_id: string;
    } | {
        type: "block_id";
        block_id: string;
    } | {
        type: "workspace";
        workspace: true;
    };
    properties?: Record<string, {
        id: string;
    }>;
    icon?: {
        type: "emoji";
        emoji: EmojiRequest;
    } | null | {
        type: "external";
        external: {
            url: TextRequest;
        };
    } | null | {
        type: "file";
        file: {
            url: string;
            expiry_time: string;
        };
    } | null;
    cover?: {
        type: "external";
        external: {
            url: TextRequest;
        };
    } | null | {
        type: "file";
        file: {
            url: string;
            expiry_time: string;
        };
    } | null;
    created_by?: PartialUserObjectResponse;
    last_edited_by?: PartialUserObjectResponse;
    created_time?: string;
    last_edited_time?: string;
    archived?: boolean;
    url?: string;
};
```

I think the :?(optional) type would be enough.

Or is there a way to avoid the following code?

```TypeScript
  const { results } = await pages();
  if ("properties" in results[0]) {
    const ti = await title(results[0]);

    if ("results" in ti) {
      if ("title" in ti.results[0]) {
        console.log(ti.results[0].title.plain_text);
      }
    }
  }
```
