### ISSUE TITLE
Typescript error when assigning null to select property

### ISSUE THREAD

**Issue by laripereira14** [makenotion/notion-sdk-js#335]
For assigning a value to a select property that could be empty when creating a page, I'm doing: 
```
"Year": {
	select: !data.year ? null : { name: data.year } 
},
```
and it works fine, the page gets created with an empty value, but typescript says that null is not assignable:
![image](https://user-images.githubusercontent.com/63196108/182397222-813d3400-4c3c-45e6-a632-83b829f90b3d.png)

**Comment by xoxohorses** [comment]
Hi @laripereira14 ! Thanks for filing an issue. We have tested this on our end an a request that looks like the following passes the typecheck:
```
const data: { year: string | null } = { year: "1882" };

const response = await notion.pages.create({
	parent: {
		database_id: "d0e59976398b4418a9fd56ed463012c4",
	},
	properties: {
		Name: {
			title: [
				{
					text: {
						content: "hi",
					},
				},
			],
		},
		Tags: {
			select: !data.year ? null : { name: data.year },
		},
	},
});
```

Can you paste your entire request? There may be a type issue with another part of the request.
