### ISSUE TITLE
why not response the total count with pagination

### ISSUE THREAD

**Issue by rowthan** [makenotion/notion-sdk-js#338]
**Describe the bug**
the `query` API did not return the total count of the query result. --  https://developers.notion.com/reference/pagination
we can't render a pagination for user.
so why not return the full information in this API?
like this:
`
{
  result: []
  total: 999,
}
`

**Expected behavior**
return the total info or add a new api named `count`?

**Comment by colin-oos** [comment]
This would be very useful for me too. Getting the count of a query is an expensive operation since I have to paginate through all the results. Would be great if there was a count api.

**Comment by lao9** [comment]
Thanks for providing this feedback! This isn't something we can easily add just yet but we've passed along this request to the team and are considering it. 👍

**Comment by mogeko** [comment]
Without this function, I have to send 3 queries at a time to load all the data, even if most users will not read the following pages...

This is very confusing. Your team would rather waste bandwidth than do such a simple optimization.
