### ISSUE TITLE
Please add support for creating mentions which are of type "template_mention"

### ISSUE THREAD

**Issue by borolepratik** [makenotion/notion-sdk-js#344]
**Describe the bug**
Unable to create pages with mentions that are of the mention type `template_mention`. Currently, mentions can be created only for `database`, `date`, `page` and `user` mention types.

I see that support for fetching template_mention was added in https://github.com/makenotion/notion-sdk-js/pull/271.

**To Reproduce**
Node version: 16.17.1
Notion JS library version: 2.2.0

```ts
const response = await notion.pages.create({
  block_id: block_id,
  properties: {
    Name: {
      title: [
        {
          text: {
            content: content,
          },
        },
      ],
    },
  },
  children: [
    {
      paragraph: {
        rich_text: [
          {
            mention: {
              // need template_mention here
            },
          },
        ],
      },
    },
  ],
});
```

**Additional context**
https://developers.notion.com/reference/rich-text#mention-objects

**Comment by lao9** [comment]
Thanks for the API request by the way; I've added this to our internal tracker - we still haven't prioritized it yet, but may get to it soon.

**Comment by borolepratik** [comment]
hi @lao9, may I request the team to prioritize this soon?

**Comment by borolepratik** [comment]
![image](https://user-images.githubusercontent.com/6431392/230727853-06e744ef-cfa2-4cc6-8feb-28083e3a4dfb.png)

Unsure if this notice means we'll ever get to create `template_mention` blocks via programmatic means.

**Comment by borolepratik** [comment]
![image](https://user-images.githubusercontent.com/6431392/230727853-06e744ef-cfa2-4cc6-8feb-28083e3a4dfb.png)
https://developers.notion.com/reference/block#template
Unsure if this notice means we'll ever get to create `template_mention` blocks via programmatic means; probably not from the looks if it.

**Comment by rhart92** [comment]
Hey @borolepratik! Happy to announce that we now support creating `template_mention`s via the public API.

Example using `createPage` if you wanted to create a page in DB template or button via the public API:

```json
{
  "parent": {
    "page_id": "...",
  },
  "properties": {},
  "children": [
    {
      "type": "paragraph",
      "paragraph": {
        "rich_text": [
          {
            "type": "mention",
            "mention": {
              "template_mention": {
                "type": "template_mention_date",
                "template_mention_date": "now",
              },
            },
          },
          {
            "type": "mention",
            "mention": {
              "template_mention": {
                "type": "template_mention_date",
                "template_mention_date": "today",
              },
            },
          },
          {
            "type": "mention",
            "mention": {
              "template_mention": {
                "type": "template_mention_user",
                "template_mention_user": "me",
              },
            },
          },
        ],
      },
  },
  ],
}
```
