### ISSUE TITLE
API token is invalid in one file but working on other

### ISSUE THREAD

**Issue by akshitkg** [makenotion/notion-sdk-js#346]
I am using notion.pages.retrieve() with mentioned guidelines to fetch a Notion page but it is showing that **API token is invalid**
![Screenshot_28](https://user-images.githubusercontent.com/92104615/192640495-a137bcea-e1f8-4132-a230-1d06b60e3ee3.png)

But, the thing is when I am using it in a function(in another file) in which I was already using notion.pages.create() (and it was working), it is working just fine.

But it is not working anyways in any file I create.

`async function fetchPage() {
  const page_id = process.env.EXPERIMENT_PAGE_ID;
  const response = await notion.pages.retrieve({ page_id: page_id });
  console.log(response);
}`

The above code is giving error but the same code is working just fine as well, as I mentioned above.

**Comment by lao9** [comment]
This seems like an environment-specific issue and you may not be importing your token into your new file directly.

That said, bug reports here only for the Node JavaScript library, only.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

Feel free to join our Slack Channel for support from other developers. [Slack Community](https://join.slack.com/t/notiondevs/shared_invite/zt-1fyckmvk6-fBOfKpDwAmi4gnjbBF3dIw)
