### ISSUE TITLE
How should I find the database id for an API request?

### ISSUE THREAD

**Issue by farzan-dehbashi** [makenotion/notion-sdk-js#347]

**Comment by borolepratik** [comment]
@farzan-dehbashi hope this helps.

https://developers.notion.com/docs/getting-started#step-2-share-a-database-with-your-integration
> The database ID is the part of the URL after your workspace name (if you have one) and the slash (myworkspace/) and before the question mark (?). The ID is 32 characters long, containing numbers and letters. Copy the ID and paste it somewhere you can easily find later.

```
https://www.notion.so/myworkspace/a8aec43384f447ed84390e8e42c2e089?v=...
                                  |--------- Database ID --------|
```

**Comment by lao9** [comment]
Thank you @borolepratik !
