### ISSUE TITLE
Missing properties in RollupFunction type

### ISSUE THREAD

**Issue by Talal-l** [makenotion/notion-sdk-js#350]
The following properties seem to be missing:
- `count_all`
- `count_unique_values`
- `count_empty`
- `count_not_empty`

https://github.com/makenotion/notion-sdk-js/blob/6c7d07a068ba8a8b2007662f3b141a7fce293dc2/src/api-endpoints.ts#L770

Also  `earliest_date` and  `latest_date` and other props are not mentioned in the [doc ](https://developers.notion.com/reference/property-item-object#rollup-property-values). Not sure if it's supposed to list all option, but I couldn't find the complete list in the doc.

**Comment by lao9** [comment]
The types in the SDK are most accurate: 
https://github.com/makenotion/notion-sdk-js/blob/6c7d07a068ba8a8b2007662f3b141a7fce293dc2/src/api-endpoints.ts#L770

I've updated the documentation to reflect that.

The old documentation values I think meant this:
- `count_all` -> `count`
- `count_unique_values` -> `unique`
- `count_empty` -> `empty`
- `count_not_empty` -> `not_empty`


Thanks so much for pointing out this inconsistency!
