### ISSUE TITLE
Use Partial<Record<string, ...>> instead of Record<string, ...>

### ISSUE THREAD

**Issue by StevenDoesStuffs** [makenotion/notion-sdk-js#353]
For example, `PageObjectResponse.properties` has a type of `Record<string, ...>`, which makes typescript think that the properties object has a value for _every_ possible key, which isn't the case. Using `Partial<Record<string, ...>>` instead would instead correctly for the user to check whether a property exists before using it. 

There are many other instances of this other than just `PageObjectResponse.properties` as well.
Also, this would obviously be a breaking change.

**Comment by lao9** [comment]
Thanks for the suggestion! For now, we plan to keep the properties type as is, but could revisit in the future. 👍

**Comment by wcauchois** [comment]
You could consider using the [--noUncheckedIndexedAccess](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#checked-indexed-accesses---nouncheckedindexedaccess) tsconfig flag.
