### ISSUE TITLE
"API token is invalid" on production

### ISSUE THREAD

**Issue by Athios-dev** [makenotion/notion-sdk-js#363]
Hi,

I am working on a web platform using **Nuxt 3** and **Notion** as my backend through this SDK. Everything is working great on localhost:3000 but when I deploy my website to Vercel, I have this error message :

`WARN @notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }`

It is really strange because I have the same `NOTION_API_KEY` (as localhost) inside my `.env`...

Here is my package.json :
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxtjs/supabase": "^0.1.16",
    "@nuxtjs/tailwindcss": "^5.1.2",
    "@tailwindcss/forms": "^0.5.2",
    "@tailwindcss/typography": "^0.5.2",
    "nuxt": "3.0.0-rc.4",
    "sass": "^1.53.0",
    "sass-loader": "^10.3.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-brands-svg-icons": "^6.1.1",
    "@fortawesome/free-regular-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/vue-fontawesome": "^3.0.1",
    "@headlessui/vue": "^1.6.4",
    "@heroicons/vue": "^1.0.6",
    "@notionhq/client": "^2.2.1",
    "highlight.js": "^11.6.0",
    "vue-gtag-next": "^1.14.0"
  }
}
```

**Screenshots**
![screen](https://user-images.githubusercontent.com/10755477/199619571-8cd628c0-bbb7-4529-9660-e35da3eb0018.png)

Have you ever encountered this scenario?
Thanks for your clarifications !

Thibaud

**Comment by Athios-dev** [comment]
I had to

**Comment by AndrejGajdos** [comment]
@Athios-dev what was the issue?
