### ISSUE TITLE
Add feature to Import Github Pull Request

### ISSUE THREAD

**Issue by marutinandanpandya** [makenotion/notion-sdk-js#367]
**Describe the bug**
Can only import issues from example mentioned at https://github.com/makenotion/notion-sdk-js/tree/main/examples/notion-github-sync
Gitub sync should also allow importing pull requests. 
As a developer, we often need to provide github link of code changes in notion pages. Having a centrallized database to track pr's will make integration easier.

1. download the current repo and `cd examples/notion-github-sync`
2. Export the configuration and execute index.js
3. All the github issues are synced

**Expected behavior**
All the pull request should also be synced

+1 for allowing organisation level github syncs.

**Comment by lao9** [comment]
Hi there, thanks for the  suggestion, but we're not currently prioritizing updating this GitHub example. 

(Unrelated to the API, we actually built an in-product GitHub sync since we first built these examples!)
https://www.notion.so/integrations/github-cdc46cd9-f0e9-48fd-b3aa-18481098e29e
