### ISSUE TITLE
Random colors assigned when creating a new "select" entry in a database

### ISSUE THREAD

**Issue by AndreMCCarvalho** [makenotion/notion-sdk-js#373]
Hey Notion,

The color property inside selects components is not working properly. In my machine I specify a color (e.g. "red") and when the page is created (to be used as a database entry) the color is randomly assigned. To replicate I would say you only need to make a post request where you have a select property specifying a color and then add it to a table.

**Comment by hazelguo** [comment]
Hi, thanks for the bug report. We are able to reproduce it, and we are working on it.
In addition, we don't actively monitor the issues in this repo, but you can submit feature requests or bug reports by emailing us at developers@makenotion.com.

**Comment by hazelguo** [comment]
The fix is merged. It should be live within a couple of days.
