### ISSUE TITLE
'Invalid request URL.' on Vercel with Next 13

### ISSUE THREAD

**Issue by carlomallone** [makenotion/notion-sdk-js#376]
We have a simple, working integration on our local environment that doesn't work on Vercel.
Logs:

```
@notionhq/client info: request start {
  method: 'post',
  path: 'databases/66d687247054487fa76cebe72f257c52/query'
}

APIResponseError: Invalid request URL.
    at worker.js:109:35529
    at worker.js:109:28521
    at <anonymous>
    at worker.js:1:3261
    at worker.js:1:3573
    at worker.js:150:11634 {
  name: 'APIResponseError',
  code: 'invalid_request_url',
  status: 400,
  headers: Headers {  },
  body: '{"object":"error","status":400,"code":"invalid_request_url","message":"Invalid request URL."}'
}

@notionhq/client debug: failed response body {
  body: '{"object":"error","status":400,"code":"invalid_request_url","message":"Invalid request URL."}'
}
```

Our environment variables are correctly set. Thank you!

**Comment by hazelguo** [comment]
Hi! Your request is with `requestHost: frontend-flax-nine.vercel.app` and we are expecting `requestHost: api.notion.com`.

In addition, we don’t actively monitor the issues in this repo. Next time please submit a bug report by emailing us at developers@makenotion.com!

**Comment by mauricekleine** [comment]
@hazelguo I'm acutally facing the same issue. How would you set the `requestHost` on the Notion client?

**Comment by gabrielesalvini** [comment]
The solution that worked for me was removing the use of experimental-edge feature of nextjs 13 in the next.config.js
`  experimental: {
    appDir: true,
    // runtime: 'experimental-edge'
  },`
