### ISSUE TITLE
Kingdutch01

### ISSUE THREAD

**Issue by kingdutch001** [makenotion/notion-sdk-js#379]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**

**To Reproduce**
Node version:
Notion JS library version:

**Expected behavior**

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by lao9** [comment]
This issue has no content?
