### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [makenotion/notion-sdk-js#382]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Notion Source plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Notion APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by rhart92** [comment]
Thanks for your interest in Notion, @yevgenypats.  We cannot take on maintenance of plug-ins for this use case; however, if you decide to build and maintain it, we're happy to provide help and technical guidance.  Please reach out to [kelsey@makenotion.com](mailto:kelsey@makenotion.com) if that's the case.
