### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by psytron** [makenotion/notion-sdk-js#386]
**Describe the bug**
 CORS errors when notion API is called directly from the browser.

**To Reproduce**
Node version: Polyfill
Notion JS library version: 2.2.3

Call API from browser.

**Expected behavior**
Expect it to return data the same way as Node.JS 

**Screenshots**
<img width="777" alt="Screen Shot 2023-02-22 at 3 38 00 PM" src="https://user-images.githubusercontent.com/7834453/220788447-06f6e7ac-80a0-4574-b076-7102769eb8c6.png">

**Additional context**
With web3 and new pkg solutions like esbuild and esinstall, node can be polyfilled, and apps or widgets on our website can call API directly, ( instead of running a redundant and unnecessary proxy/relay server, or maintaining a server just so our web widgets can call a simple API . )  We realize that some older API still block browser requests and limit their API to server only. Just wanted to check in and see if there are some headers or special request parameters to call notion API directly from our browser based app.

**Comment by rhart92** [comment]
Hey @psytron, we don't currently support requests from the browser. Some folks have suggested possible work-arounds in this [issue](https://github.com/makenotion/notion-sdk-js/issues/96), but please note that we don't suggest making API calls directly from the browser for security reasons.

**Comment by psytron** [comment]
Thanks @rhart92.  We looked at the work-arounds in issue #96, as you recommended.  

Can you elaborate on the security reasons you mentioned?
