### ISSUE TITLE
the result rows of “query database” are not the exact order in which they're displayed on notion

### ISSUE THREAD

**Issue by Holybasil** [makenotion/notion-sdk-js#388]
**Describe the bug**
the default order of API response matches "created_time descending" rather than the real order on notion page

**To Reproduce**
Node version: 2.1.11
Notion JS library version: 2.2.3

```
const response = await notion.databases.query({
    database_id: databaseId
})
```

**Expected behavior**
return rows just same as list on notion page when empty sorts 

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**
no

**Comment by rhart92** [comment]
Hi @Holybasil, unfortunately ordering of rows is a property of the database view and views aren't currently supported via the API. We do support customizing the sort via `queryDatabase` by passing a `sorts` key. ([docs](https://developers.notion.com/reference/post-database-query-sort))
 
An example body for `queryDatabase` that filters and sorts is shown below:

```json
{
  "filter": {
    "or": [
      {
        "property": "In stock",
        "checkbox": {
          "equals": true
        }
      },
      {
        "property": "Cost of next trip",
        "number": {
          "greater_than_or_equal_to": 2
        }
      }
    ]
  },
  "sorts": [
    {
      "property": "Last ordered",
      "direction": "ascending"
    }
  ]
}
```

Hope this helps! 🙇

**Comment by JClackett** [comment]
This would be pretty nice though - I wana be able to reorder a database in notion and then see the order update on my website (using notion as a CMS)!

**Comment by rhart92** [comment]
Agreed! We are tracking this as a feature and will update when it's supported.

**Comment by JClackett** [comment]
@matthewmueller thats what ive done so far, just annoying having to manually set a number, and then if you wana move something to the top, every single row has to be updated :(

**Comment by busyhe** [comment]
updated 2025-09-03， not the exact order in which they're displayed on notion

<img width="572" height="274" alt="Image" src="https://github.com/user-attachments/assets/c5c50ac6-62f9-4043-887b-125899c106a7" />
