### ISSUE TITLE
502 OPTIMIZED_EXTERNAL_IMAGE_REQUEST_UNAUTHORIZED error

### ISSUE THREAD

**Issue by esau-morais** [makenotion/notion-sdk-js#392]
**Describe the bug**

In Next.js, when an image is requested, it returns 502

Node version: 18.*
Notion JS library version: 2.2.3

[repo](https://github.com/esau-morais/emots.dev)

**Screenshots**
![image](https://user-images.githubusercontent.com/55207584/226907342-66c1eb82-88f7-4f22-bb52-2a7223543b9f.png)

**Comment by rhart92** [comment]
I'm not sure I follow how this is related to the this repo. Can you please provide more details of what you are trying to do and what's failing?

**Comment by esau-morais** [comment]
this happens when i try to fetch images from notion using next.js and the notion sdk. i don't know what causes the problem, but sometimes images simply are not public, but then after refreshing a few times, the website gets to show them as expected.

some possible causes:
domaing propagation
notion bug

if it is helpful, i'll drop [here](https://github.com/esau-morais/emots.dev) the repo
