### ISSUE TITLE
This is not really a pure javascript library

### ISSUE THREAD

**Issue by fabiocarneiro** [makenotion/notion-sdk-js#395]
**Describe the bug**
Although the name of the repository is "notion-sdk-js" and the readme says "[Notion SDK for JavaScript](https://github.com/makenotion/notion-sdk-js#notion-sdk-for-javascript)", this library is not compatible with any Javascript environment.

**To Reproduce**
Node version: ? (actually not using a node.js runtime environment)
Notion JS library version: 2.2.3

I tried to use this library in a javascript runtime environment different than nodejs, and I was not able due to the missing libraries.

**Expected behavior**

Option 1: Rename the repository to "notion-sdk-nodejs", update the readme to "Notion SDK for Node.js"
Option 2: Cease the dependency on "node-fetch" and provide mechanisms that other fetch implementations can be provided.

**Comment by Xheldon** [comment]
Notion js api only works in node env, not in browser

**Comment by fabiocarneiro** [comment]
I'm not even trying in Browser. I was trying to use another JavaScript environment (Google Apps Script) where the node libraries are not available.

**Comment by rhart92** [comment]
@fabiocarneiro, the option #2 that you mentioned is implemented. All you need to do is instantiate the `Client` with your desired `fetch` implementation which should allow you to use in any javascript environment. ([code](https://github.com/makenotion/notion-sdk-js/blob/main/src/Client.ts#L91))
