### ISSUE TITLE
Add custom configuration for the Fetch Client

### ISSUE THREAD

**Issue by askides** [makenotion/notion-sdk-js#415]
Hello Team!

I'm currently running this SDK under Next.js 13 using server components, everything works fine, but I would like to set some tags to the fetch request in order to leverage the caching function of Vercel.

The feature is explained here: https://nextjs.org/docs/app/api-reference/functions/revalidateTag.

And that's basically what I want to do:

`fetch(url, { next: { tags: [...] } });`

Currently, I already added the custom Next.js fetch to the Notion Client through the dedicated property, but this is the only thing I can do.

Any idea about how can I solve this problem?

**Comment by tobbbe** [comment]
You can use a custom fetch when you create your client:
```typescript
const notionClient = new Client({
  auth: process.env.NOTION_SECRET,
  fetch: (url, opts) => {
    return fetch(url, {
      ...opts,
      next: { tags: ['notion'] },
      cache: 'force-cache',
    })
  },
})
```

**Comment by linkyndy** [comment]
I was looking at this exact same issue. However, I need to get one step further: I need to set tags dynamically, on a per operation basis (that's for being able to independently invalidate certain pages). How shall I go around that? Creating a separate client before every operation sounds a bit pointless, but I don't think a custom `fetch` can be passed to client methods (i.e. `notionClient.pages.retrieve`, to build on the example above)?
