### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by vashisth00** [makenotion/notion-sdk-js#417]
Describe the bug
When attempting to fetch data from the Notion API using the Node JavaScript library, a CORS error occurs. The error message states: "Access to fetch at 'https://api.notion.com/v1/databases/285e6842792b467393a5487fdf2619a2/query' from origin 'https://pedv-website.vercel.app/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

To Reproduce
Node version: 18
Notion JS library version:   "@notionhq/client": "^2.2.5"

Run the provided code that attempts to fetch data from the Notion API.
Observe the CORS error in the browser console or terminal.
Expected behavior
The code should successfully fetch data from the Notion API without encountering a CORS error.

Screenshots
<img width="1458" alt="Screenshot 2023-07-08 at 05 15 20" src="https://github.com/makenotion/notion-sdk-js/assets/29851545/410ec831-414d-404f-b07d-d5d603e84d6c">

Additional context
The error message suggests that the Notion API response is missing the necessary Access-Control-Allow-Origin header, resulting in the CORS error. This issue occurs when accessing the API from a different ori

**Comment by rhart92** [comment]
Hey @vashisth00, to avoid encouraging having API tokens sent to the browser we don't allow making requests to the Notion API from a browser. You'll have to make the request from a server and then send those results to the browser 🙏
