### ISSUE TITLE
Heading blocks do not have the `is_toggleable` property in their types

### ISSUE THREAD

**Issue by huw** [makenotion/notion-sdk-js#420]
[The specification says](https://developers.notion.com/reference/block#headings) that `heading_1`, `heading_2`, and `heading_3` blocks should have an `is_toggleable` property within the `heading_x` property. I have verified against the API that it is reporting this data correctly (and therefore returning it through the client), but it is not typed correctly in the library.

While it is present inside [`BlockObjectRequest`](https://github.com/makenotion/notion-sdk-js/blob/550c51c68ed7b6c077ab376c5535af0faed2d54f/src/api-endpoints.ts#L6690), [`BlockObjectRequestWithoutChildren`](https://github.com/makenotion/notion-sdk-js/blob/550c51c68ed7b6c077ab376c5535af0faed2d54f/src/api-endpoints.ts#L6067), [`UpdateBlockBodyParameters`](https://github.com/makenotion/notion-sdk-js/blob/550c51c68ed7b6c077ab376c5535af0faed2d54f/src/api-endpoints.ts#L10020), it is not present inside `BlockObjectResponse` (specifically [`Heading1BlockObjectResponse`](https://github.com/makenotion/notion-sdk-js/blob/550c51c68ed7b6c077ab376c5535af0faed2d54f/src/api-endpoints.ts#L4792), `Heading2BlockObjectResponse`, and `Heading3BlockObjectResponse`). I’d normally submit a PR but I’m aware that `api-endpoints.ts` is auto-generated; I’ve patched the library for my own usage.

This is somewhat related to #245, although I believe @aalemayhu was using a version of the API before the `is_toggleable` property was included in the response.

**Comment by aalemayhu** [comment]
I was not aware of `is_toggleable`, Thanks!
