### ISSUE TITLE
AB$ Java

### ISSUE THREAD

**Issue by ASISBusiness** [makenotion/notion-sdk-js#422]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**

**To Reproduce**
Node version:
Notion JS library version:

**Expected behavior**

**Screenshots**
Please include any screenshots that help explain your problem.

**Additional context**

**Comment by ASISBusiness** [comment]
> Report bugs here only for the Node JavaScript library.
> 
> If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Node version:
> Notion JS library version:
> 
> Steps to reproduce the behavior:
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> Please include any screenshots that help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by rhart92** [comment]
Since there doesn't seem to be any information in this issue, closing.
