### ISSUE TITLE
Notion API needs better outage monitoring and reporting!

### ISSUE THREAD

**Issue by skeddles** [makenotion/notion-sdk-js#424]
**Describe the bug**
RequestTimeoutError: Request to Notion API has timed out

(not sure if this is a problem with the client or server because I can't find any status page or messaging saying the team is aware of it, so I'm opening it in case updates to this library are the problem)

**To Reproduce**
Node version: v16.17.0
Notion JS library version: 2.2.7

`await notion.databases.query({database_id: ID});`
wait 30 seconds

EDIT: eventually this problem resolved itself, then i started getting database not found errors. eventually those cleared up too.

**Expected behavior**
API works

**Screenshots**
no

**Additional context**
no

**Comment by stephanschubert** [comment]
Just encountered the same problem.. worked like 1 hour ago.

**Comment by paix26875** [comment]
I have the same problem.

Node version: v18.16.1
Notion JS library version: 2.2.3

Error
```
@notionhq/client warn: request fail {
  code: 'notionhq_client_request_timeout', message: 'Request to Notion API has
  message: 'Request to Notion API has timed out'
}
```

I have a program that Inserts data into the Database in Notion that runs every hour on a scheduled run.
As of 2023-07-20 01:00, the process is failing with the same error from 2023-07-19 14:30 to 2023-07-20 00:30. All dates and times are in Universal Standard Time.

**Comment by TomFrankly** [comment]
Same problem here.

Node 18.x on Pipedream.

**Comment by paix26875** [comment]
This error seems to have settled down for me.
I have not encountered the error from 2023-07-20 02:30 to 2023-07-20 07:30.

**Comment by skeddles** [comment]
Same, it works fine now. 

What is more worrying is I contacted Notion support and they said they didn't see any problem at all.

Notion clearly need to implement better monitoring for when their services go down, and they need to communicate these outages with us. I checked the dev website and there was no notice or status page, and I checked their dev twitter and there was no news (despite the last tweet being outage related).

**Comment by parulbaweja** [comment]
Hi there! Thanks so much for the report and we apologize for any inconvenience. Unfortunately, we were not able to identify an incident that occurred during the timeframe reported. As a general rule, please report issues (such as failed responses) to our Support team, so we can get you a detailed investigation.

A few folks posted that querying a database was returning a timeout error: if you receive a 503 or 504, please try your request again, as we have certain timeouts instituted (e.g. database timeouts) to protect resources. In general, we are prioritizing a project to improve support for large databases in H2, as well as improving our monitoring. We’re sorry for the inconvenience and hope to make improvements here soon!

**Comment by TomFrankly** [comment]
Hi @parulbaweja,

As are as we could tell, a big part of this is that it wasn't responding with a status code at all. We got the same "RequestTimeoutError: Request to Notion API has timed out" code in Pipedream, but no status code in the error message, and no header info.

Our code is set up with the async-retry npm package and set to retry calls up to 2 times when encountering a 500-level error, and in this instance that code didn't get a chance to run due to the lack of status code.
