### ISSUE TITLE
error about CORS when use API

### ISSUE THREAD

**Issue by xiazhaohui** [makenotion/notion-sdk-js#458]
**Describe the bug**
now i have a question

i wanna use notion api get my notio database's data, and i find the API is 
`const myPage = await notion.databases.query({
  database_id: "MY_KEY"
})`

but, when i do it, i got the error notice: request doesn't pass access control check
<img width="673" alt="image" src="https://github.com/makenotion/notion-sdk-js/assets/82207908/7c7f537e-2cb6-4674-8245-a82309d20d3b">

i wanna know how to solve the CORS problem, any people can tell me? thanks a lot 

**To Reproduce**
Node version: v16.16.0
Notion JS library version: "@notionhq/client": "^2.2.13",

**Comment by Lev-Shapiro** [comment]
I believe what you need is a web version of the Notion API because, as I've checked, running the same code on Node.js doesn't result in such an issue

**Comment by rhart92** [comment]
Due to security concerns of exposing API tokens in the browser, Notion public API requests aren't able to be made from a web browser. You'll have to make the requests server side and then send the results to the browser. Apologies for any inconvenience.

**Comment by xiazhaohui** [comment]
> I believe what you need is a web version of the Notion API because, as I've checked, running the same code on Node.js doesn't result in such an issue

i got it, thank you very much @Lev-Shapiro

**Comment by xiazhaohui** [comment]
> Due to security concerns of exposing API tokens in the browser, Notion public API requests aren't able to be made from a web browser. You'll have to make the requests server side and then send the results to the browser. Apologies for any inconvenience.

Thanks for answering questions @rhart92 
I wonder if there is a better way to use Notion API in the web env?
