### ISSUE TITLE
Wrong types for MultiSelectPropertyValue

### ISSUE THREAD

**Issue by pbteja1998** [makenotion/notion-sdk-js#46]
It seems that types are wrong for `MultiSelectPropertyValue`. Instead of an array, `multi_select` is defined as a normal object.

---

## Code

<img width="1437" alt="Screenshot 2021-05-14 at 5 20 39 AM" src="https://user-images.githubusercontent.com/17903466/118201031-30087a00-b474-11eb-98d9-2552776edead.png">

<img width="1437" alt="Screenshot 2021-05-14 at 5 20 24 AM" src="https://user-images.githubusercontent.com/17903466/118201029-2f6fe380-b474-11eb-8784-44440a3ebc95.png">

<img width="1437" alt="Screenshot 2021-05-14 at 5 19 52 AM" src="https://user-images.githubusercontent.com/17903466/118201018-2bdc5c80-b474-11eb-853b-3b2ed2fdf831.png">

---

## Docs

<img width="1437" alt="Screenshot 2021-05-14 at 5 21 58 AM" src="https://user-images.githubusercontent.com/17903466/118201093-53cbc000-b474-11eb-8652-473809f21371.png">

**Comment by aoberoi** [comment]
Good catch, thank you!

**Comment by blackmad** [comment]
this has been fixed in v0.1.5!
