### ISSUE TITLE
In version 2.2.13: QueryDatabaseResponse response types include PartialDatabaseObjectResponse | DatabaseObjectResponse 

### ISSUE THREAD

**Issue by dsieczko** [makenotion/notion-sdk-js#467]
I get errors trying to use the response from `notion.databases.query` because the type `QueryDatabaseResponse `can include all of `PageObjectResponse | PartialPageObjectResponse | PartialDatabaseObjectResponse | DatabaseObjectResponse` when really it should just be `PageObjectResponse | PartialPageObjectResponse` like in version 2.2.3

**Comment by rhart92** [comment]
With the addition of [Wikis](https://www.notion.so/help/wikis-and-verified-pages), databases can now contain other databases. You should be able to use type guards so you can handle `PageObjectResponse | PartialPageObjectResponse` separately from `PartialDatabaseObjectResponse | DatabaseObjectResponse`.
