### ISSUE TITLE
unrelated to js lib 

### ISSUE THREAD

**Issue by bdytx5** [makenotion/notion-sdk-js#516]
not sure where to report bugs for the core notion app, so I just figured I would do it here 

a few issues: 

Command + A does not work. Given that its supported in virtually every text input field, it should be in notion 

using the arrows to navigate text behaves very strangely, sometimes simply arrowing up does not work (eg it skips lines in a seemingly unpredictable manner)

**Comment by arunsathiya** [comment]
team@makenotion.com for support, if you're on one of the paid plans. I don't know if that email address actively drops free tier requests.

**Comment by bdytx5** [comment]
its just a suggestion. I dont need support

**Comment by arunsathiya** [comment]
Yeah, but it makes more sense to forward this to the support team so that they can track it internally on a relevant bug tracker. The current one is just focused on the JS/TS SDK.
