### ISSUE TITLE
`Can't resolve 'http2'`for React & `Can't resolve 'dns'` for Next,js

### ISSUE THREAD

**Issue by nbr41to** [makenotion/notion-sdk-js#53]
I want to use the Notion API.
Can these be used in React?
I wrote it like this.
```
import { Client } from '@notionhq/client';

function App() {
  const notion = new Client({ auth: process.env.REACT_APP_INTEGRATION_TOKEN });
  return (
    <div className="App">
    // ...more

```
In Next.js, `Module not found: Can't resolve 'dns'`.
In CRA, `Module not found: Can't resolve 'http2'`.
is displayed.

package.json
```
{
  "name": "lesson-notion-api",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@notionhq/client": "^0.1.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by ilyapasyuk** [comment]
I have the same problem

**Comment by aoberoi** [comment]
Thanks for describing what you're hoping to accomplish. At this time, this project doesn't support what you've described. But it might be something we add! Let's discuss it over in #60. I'm going to close this issue so I can funnel several discussions together.

**Comment by JorritKeijzer** [comment]
Hi, issue #60 doesn't exist. @aoberoi. Is there a fix available?

**Comment by vtrikoupis** [comment]
It seems to be relying on the deprecated http2 npm module. Adding a node engine with version <9.0.0 might work but I'd also like that the http2-wrapper uses the native node http2 module

**Comment by conradlin** [comment]
Bumping this issue. It seems like on next.js I can only have the line

`import { Client } from '@notionhq/client';` 

if I am also running a getStaticProps to fetch the details at build time of the page. Otherwise, I get a bunch of errors for:

Module not found: Can't resolve 'dns'
Module not found: Can't resolve 'http2'
Module not found: Can't resolve 'fs'
Module not found: Can't resolve 'net'
Module not found: Can't resolve 'tls'

**Comment by janzheng** [comment]
Using this on the Svelte client, getting same error. No problem running in server-side using Sapper
