### ISSUE TITLE
`databases.list` not returning any databases.

### ISSUE THREAD

**Issue by julianbenegas** [makenotion/notion-sdk-js#56]
`notion.databases.list` is returning no results. Code is something like:

```ts
import { NextApiRequest, NextApiResponse } from "next"
import { notion } from "../../lib/notion"

export default async (req: NextApiRequest, res: NextApiResponse) => {
  console.log(await notion.users.list({})) // This one is returning all our users, so the integration works.
  console.log(await notion.databases.list({})) //  This one is returning { ..., results: [] }, an empty array.

 // btw, to both methods I have to pass an empty object else typescript will complain, which is odd.

  res.status(200).send("ok")
}
```

We have lots of databases on our workspace, and a couple of them are even public to the whole web.

**Comment by ramnes** [comment]
You need to share with the integration user. :)

**Comment by julianbenegas** [comment]
yeah, sorry, read it just now 🙈

**Comment by luigimoyano** [comment]
I have exactly the same problem... I have shared the database with the integration but it does get nothing

**Comment by terwer** [comment]
+1.I have exactly the same problem... I have shared the database with the integration but it does get nothing

**Comment by terwer** [comment]
I use the search api.also return empty results.
