### ISSUE TITLE
Incorrect Types for Blocks

### ISSUE THREAD

**Issue by ivoberger** [makenotion/notion-sdk-js#58]
All Block types currently have types with a `text` key, `paragraph` type as an example here:
```ts
export interface ParagraphBlock extends BlockBase {
    type: 'paragraph';
    text: RichText[];
    children?: BlockBase[];
}
```
The [documentation](https://developers.notion.com/reference/block#paragraph-blocks) however states that the text for paragraphs is actually found in a a key `paragraph`, for headings it's in `heading_#` and so on. When using the API the text is where the API reference states it is, so it's just the types which are wrong here.

**Comment by aoberoi** [comment]
Good catch, thank you!
