### ISSUE TITLE
Get raw data for unsupported blocks 

### ISSUE THREAD

**Issue by pbteja1998** [makenotion/notion-sdk-js#61]
Not sure if this is the right place to ask this. But, it would really help if we can get the data for the unsupported blocks. It doesn't matter even if it's not structured properly. When you do add support for those blocks, you can add a proper structure to it.

**Comment by yassinebridi** [comment]
I would love to see this being worked on, because even the simplest of blocks right now, like images, are not supported.

**Comment by JClackett** [comment]
Is there a timeline for how long it will be until images are supported? would really appreciate it!

**Comment by jhartquist** [comment]
Hoping for code blocks as well.  Thanks!

**Comment by alfonsodlopez** [comment]
Hi All, the team here is looking into supporting more, advanced blocks and currently laying the groundwork to enable additional features. We do not have a public roadmap or timeline we can offer at this time. I've taken the feedback here and added it to our internal feedback tracker and given it some weight (based on the thumbs up). If there are other feature requests specific to the API (independent of the SDK) please send them over to developers@notion.com.
