### ISSUE TITLE
How do I delete a database item?

### ISSUE THREAD

**Issue by giuseppecrj** [makenotion/notion-sdk-js#68]
First of all, I want to thank everyone at notion for the API 👏🏼 🥳 

My question is how would I go about deleting a database item using the JS SDK? 

I've tried the following but no go:
```
await notion.request({
    path: `pages/${data.pageId}`,
    method: 'DELETE',
    body: {
        parent: { database_id: databaseId }
    }
})
```

**Comment by nabildroid** [comment]
the API doesn't yet supports deleting items

**Comment by alicial** [comment]
We support delete through the update page endpoint, by setting the `archived` parameter: https://developers.notion.com/reference/patch-page#archive-delete-a-page

This was missing from the library, the above PR will add it.
