### ISSUE TITLE
http2 error when used with create-react-app apps

### ISSUE THREAD

**Issue by juleshwar** [makenotion/notion-sdk-js#71]
Running into issues related to `http2` when used with a react application created using `create-react-app`.   
[Link to test repo](https://github.com/juleshwar/notion-sdk-test)

## How to reproduce
1. Create an app using `create-react-app`
2. Add `@notionhq/client` as a dependency
3. Add `const { Client } = require("@notionhq/client")` to `App.js`  

## Screenshot
![image](https://user-images.githubusercontent.com/24788774/118402360-420e3680-b687-11eb-8e5a-f1d78b0135bd.png)

**Comment by jyash97** [comment]
Hey @juleshwar 

You can check the discussion over here: #60

**Comment by moonrise-tk** [comment]
It seems discussions are closed. Can we get a TLDR of how to resolve this issue?

**Comment by juleshwar** [comment]
@moonrise-tk 
Looks like the discussion has been deleted.  
The gist of it was that currently this sdk is **not supposed to be used in a browser environment.** You can use it in a node.js environment in the server.
