### ISSUE TITLE
MultiSelectPropertyValue Typescript Bug

### ISSUE THREAD

**Issue by kevarifin14** [makenotion/notion-sdk-js#74]
The MultiSelectPropertyValue type has a bug where it expects the multi_select to be a single SelectOption instead of an array of SelectOption[]

```
export interface MultiSelectPropertyValue extends PropertyValueBase {
    type: 'multi_select';
    multi_select: {
        id: string;
        name: string;
        color: Color;
    };
}
```

**Comment by blackmad** [comment]
should fixed in v0.1.5 - let me know if you have any issues!
