### ISSUE TITLE
Empty String in text-content and Null Values in link, href

### ISSUE THREAD

**Issue by nitincodery** [makenotion/notion-sdk-js#78]
I created a database of few pages and added **page mentions** to the default Name property.

I'm getting this as in Name property of each page when querying the database.

```
"id":"title",
"type":"title",
"title":[
   {
      "type":"text",
      "text":{
         "content":" ",
         "link":null
      },
      "annotations":{
         "bold":false,
         "italic":false,
         "strikethrough":false,
         "underline":false,
         "code":false,
         "color":"default"
      },
      "plain_text":" ",
      "href":null
   }
]
```
I should get content as page mention title and link as its notion public page url.

Is this fine?

**Comment by lao9** [comment]
Hey @nitincodery - as of right now, mentions to public pages will be omitted unless the integration has been explicitly added to the page. I'll be trying to update the ReadMe documentation to ensure that is more clear!

**Comment by lao9** [comment]
@nitincodery - We no longer completely "omit" mentions that an integration does not have access to, but we'll at least return the mention with the mentioned page id and url, but the title of the page will be omitted: https://developers.notion.com/reference/rich-text#page-mentions

For public pages, integrations still must be explicitly added to have access.
