### ISSUE TITLE
`PropertyValue` type expects `id` and `type` when updating

### ISSUE THREAD

**Issue by simster7** [makenotion/notion-sdk-js#84]
When implicitly using the `PropertyValue` type to update a page's property, TypeScript requires that the `id` and `type` fields be included.

Example:
```ts
notion.pages.update({
    page_id: taskId,
    properties: {
        'Do On': {
            date: {
                start: '2021-05-20'
            }
        }
    }
})
```

Gives the following error:

```
test.ts:41:13 - error TS2322: Type '{ date: { start: string; }; }' is not assignable to type 'PropertyValue'.
  Type '{ date: { start: string; }; }' is missing the following properties from type 'DatePropertyValue': type, id

41             'Do On': {
```

As per the example on [this page](https://developers.notion.com/reference/patch-page), these fields should not be required. Furthermore, if this request is made fully in JS it works without a problem.

![image](https://user-images.githubusercontent.com/614838/119038351-e1714900-b967-11eb-9b0d-332418afadc5.png)

The trivial fix would be to make these fields optional:
```ts
export interface PropertyValueBase {
    id?: string;
    type?: string;
}
```

But (perhaps obviously), this is probably not desirable. Perhaps `PagesUpdateBodyParameters` should use something like `PropertyUpdateValue` where these values are optional?

I'd be more than happy to work on a PR for this issue if necessary.

**Comment by blackmad** [comment]
this is fixed in the new v0.1.5 version, please let me know if you have any issues with it!
