### ISSUE TITLE
Could not add options that are not in select when adding new data

### ISSUE THREAD

**Issue by shyjal** [makenotion/notion-sdk-js#90]
I am adding data to the database using post request to /pages. 

It only works when I give {name: value} when value is already defined as an option in the notion table.

If a new option is provided, the following error message shows up

`rZ?P is an invalid select option`

**Comment by alicial** [comment]
We now support adding new options dynamically: https://developers.notion.com/changelog/select-values-can-now-be-dynamically-created-via-create-and-update-page-endpoints-other-updates-since-public-beta-launch
