### ISSUE TITLE
Text type property missing/invalid

### ISSUE THREAD

**Issue by KoditkarVedant** [makenotion/notion-sdk-js#93]
I'm not sure if it is missing in SDK or the dummy success response given in API document are incorrect.. 

If you see the API response for `List Databases` & `Retrieve a database` API's you will notice that there is Property with the type `text` and when I look into source code I do not see any Text type property. 

Would it possible for anyone to clear this confusion for me?

[code](https://github.com/makenotion/notion-sdk-js/blob/5a6f2fac088cb06a03b01b0b75c47790af3b0bbb/src/api-types.ts#L145)

code screenshot: 
![image](https://user-images.githubusercontent.com/18693839/119237752-147c2e00-bb5c-11eb-825c-412c2fcfd2fa.png)

API document
[Retrieve a database](https://developers.notion.com/reference/get-database)
[List databases](https://developers.notion.com/reference/get-databases).

**Comment by blackmad** [comment]
I believe that the documentation & typescript types are correct - the "Text" type in the notion frontend corresponds to the "rich_text" type in the API & client library. You can see working examples here: https://github.com/makenotion/notion-sdk-js/blob/main/examples/generate-random-data/index.ts

It looks like the examples in the right hand column of the API docs need to be updated from "text" to "rich_text" cc @97agupta

**Comment by alicial** [comment]
Hi @KoditkarVedant, thanks for raising this issue, we have corrected the API docs to `rich_text`.
